In [24]:
from pathlib import Path

import geopandas as gpd
import networkx as nx
import osmnx as ox
import polars as pl

In [25]:
ROOT_PATH = Path(".").resolve().absolute()
DATASET_PATH = ROOT_PATH / "sumo/simulations/ohare-chicago-junctionless/output/fcd.parquet"
NETWORK_PATH = ROOT_PATH / "networks/graphml/ohare_network.graphml"

In [26]:
G = ox.load_graphml(NETWORK_PATH)
edges_gdf = ox.graph_to_gdfs(G, nodes=False, fill_edge_geometry=True).to_crs(epsg=4326)
edges_gdf

,,,osmid,highway,lanes,name,oneway,ref,reversed,length,geometry,maxspeed,bridge
u,v,key,,,,,,,,,,,
1153867776,29839280,0,985432262,primary,3,Mannheim Road,True,US 12;US 45,False,22.870702,"LINESTRING (-87.87914 41.9887, -87.87925 41.98...",NaN,NaN
29839280,1153867817,0,985432262,primary,3,Mannheim Road,True,US 12;US 45,False,38.594048,"LINESTRING (-87.87925 41.98889, -87.87943 41.9...",NaN,NaN
1153867781,1153867758,0,11537207,motorway_link,1,NaN,True,NaN,False,30.909291,"LINESTRING (-87.88111 41.98211, -87.88126 41.9...",NaN,NaN
1153867758,102856723,0,11537207,motorway_link,1,NaN,True,NaN,False,19.860727,"LINESTRING (-87.88126 41.98185, -87.88133 41.9...",NaN,NaN
29786118,4686227143,0,320340442,tertiary,3,Bessie Coleman Drive,True,NaN,False,95.216379,"LINESTRING (-87.88573 41.97871, -87.88573 41.9...",30 mph,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
29785981,5037315526,0,31296557,unclassified,2,O'Hare International Terminal Departures,True,NaN,False,8.552609,"LINESTRING (-87.89083 41.97663, -87.89092 41.9...",20 mph,NaN
1153867719,102857949,0,11537330,motorway_link,NaN,NaN,True,NaN,False,15.968346,"LINESTRING (-87.87667 41.97976, -87.87658 41.9...",NaN,NaN
1153867766,102855117,0,19012965,motorway_link,1,NaN,True,NaN,False,22.372636,"LINESTRING (-87.88105 41.98147, -87.88105 41.9...",NaN,NaN
1153867761,1153867763,0,19012965,motorway_link,1,NaN,True,NaN,False,15.529217,"LINESTRING (-87.87978 41.98228, -87.87961 41.9...",NaN,NaN
1153867763,102855124,0,19012965,motorway_link,1,NaN,True,NaN,False,13.881163,"LINESTRING (-87.87961 41.98223, -87.87947 41.9...",NaN,NaN

In [27]:
lf = pl.scan_parquet(DATASET_PATH)
df = lf.collect()
df.to_pandas()

,vehicle_id,geo_position,time,raw_lane_id,mapped_lane_id,edge_id,reversed,node_mapped_id,lon,lat
0,0,"[-87.8856713296918, 41.99494072305388]",0.5,1188647984_0,1188647984_0,1188647984,False,1188647984,-87.885671,41.994941
1,0,"[-87.88567733180858, 41.994936271618215]",1.0,1188647984_0,1188647984_0,1188647984,False,1188647984,-87.885677,41.994936
2,0,"[-87.88568911243644, 41.994927534580114]",1.5,1188647984_0,1188647984_0,1188647984,False,1188647984,-87.885689,41.994928
3,0,"[-87.88570568973026, 41.99491498626672]",2.0,:263785883_1_0,:263785883_1_0,321574768,False,node_263785883,-87.885706,41.994915
4,0,"[-87.88572492532072, 41.994900100759565]",2.5,:263785883_1_0,:263785883_1_0,321574768,False,node_263785883,-87.885725,41.994900
...,...,...,...,...,...,...,...,...,...,...
859435,1702,"[-87.88874921463292, 41.99804074104869]",4081.5,:10021303714_0_0,:10021303714_0_0,1094214001,False,node_10021303714,-87.888749,41.998041
859436,1702,"[-87.88875558331904, 41.99798545992872]",4082.0,1094214001_0,1094214001_0,1094214001,False,1094214001,-87.888756,41.997985
859437,1702,"[-87.88875619867935, 41.997933337316766]",4082.5,1094214001_0,1094214001_0,1094214001,False,1094214001,-87.888756,41.997933
859438,1702,"[-87.88875677920512, 41.99788060455132]",4083.0,1094214001_0,1094214001_0,1094214001,False,1094214001,-87.888757,41.997881
859439,1702,"[-87.88875741688537, 41.997827322479466]",4083.5,1094214001_0,1094214001_0,1094214001,False,1094214001,-87.888757,41.997827

In [28]:
df.describe()

shape: (9, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ statistic ┆ vehicle_i ┆ geo_posit ┆ time      ┆ … ┆ reversed ┆ node_mapp ┆ lon       ┆ lat       │
│ ---       ┆ d         ┆ ion       ┆ ---       ┆   ┆ ---      ┆ ed_id     ┆ ---       ┆ ---       │
│ str       ┆ ---       ┆ ---       ┆ f64       ┆   ┆ f64      ┆ ---       ┆ f64       ┆ f64       │
│           ┆ f64       ┆ f64       ┆           ┆   ┆          ┆ str       ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ count     ┆ 859440.0  ┆ 859440.0  ┆ 859440.0  ┆ … ┆ 859440.0 ┆ 859440    ┆ 859440.0  ┆ 859440.0  │
│ null_coun ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0      ┆ 0         ┆ 0.0       ┆ 0.0       │
│ t         ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ mean      ┆ 879.54122 ┆ null      ┆ 1972.4138 ┆ … ┆ 0.058079 ┆ null      ┆ -87.88910 ┆ 41.984193 │
│           ┆ 1         ┆           ┆ 52        ┆   ┆          ┆           ┆ 4         ┆           │
│ std       ┆ 507.30202 ┆ null      ┆ 1029.8529 ┆ … ┆ null     ┆ null      ┆ 0.007366  ┆ 0.006624  │
│           ┆ 8         ┆           ┆ 68        ┆   ┆          ┆           ┆           ┆           │
│ min       ┆ 0.0       ┆ null      ┆ 0.5       ┆ … ┆ 0.0      ┆ null      ┆ -87.90627 ┆ 41.973193 │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ 2         ┆           │
│ 25%       ┆ 443.0     ┆ null      ┆ 1092.5    ┆ … ┆ null     ┆ null      ┆ -87.89288 ┆ 41.978784 │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ 9         ┆           │
│ 50%       ┆ 872.0     ┆ null      ┆ 1965.5    ┆ … ┆ null     ┆ null      ┆ -87.88574 ┆ 41.982073 │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ 3         ┆           │
│ 75%       ┆ 1323.0    ┆ null      ┆ 2851.5    ┆ … ┆ null     ┆ null      ┆ -87.88558 ┆ 41.98961  │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ 2         ┆           │
│ max       ┆ 1758.0    ┆ null      ┆ 4083.5    ┆ … ┆ 1.0      ┆ null      ┆ -87.87623 ┆ 41.999815 │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ 1         ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

In [29]:
result = edges_gdf.reset_index().set_index("osmid").loc[321574770.0][["u", "v"]].values.tolist()
result

[np.int64(7710696745), np.int64(5493833658)]

In [30]:
from functools import lru_cache


@lru_cache(maxsize=None)
def ensure_connection(
    G_road: nx.MultiDiGraph, source: int, target: int
) -> list[int] | None:
    try:
        path = nx.shortest_path(G_road, source=source, target=target, weight="length")
        edges_path = list((x, y, 0) for x, y in zip(path[:-1], path[1:]))
        edge_data = list(G.edges[edge]["osmid"] for edge in edges_path)
        res = []
        for ed in edge_data:
            if ed not in res:
                res.append(ed)
        return res

    except nx.NetworkXNoPath:
        return None

In [31]:
df.filter(pl.col("node_mapped_id").cat.starts_with("node_"))

shape: (80_031, 10)
┌────────────┬────────────┬────────┬────────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ vehicle_id ┆ geo_positi ┆ time   ┆ raw_lane_i ┆ … ┆ reversed ┆ node_mapp ┆ lon       ┆ lat       │
│ ---        ┆ on         ┆ ---    ┆ d          ┆   ┆ ---      ┆ ed_id     ┆ ---       ┆ ---       │
│ i64        ┆ ---        ┆ f64    ┆ ---        ┆   ┆ bool     ┆ ---       ┆ f64       ┆ f64       │
│            ┆ array[f64, ┆        ┆ cat        ┆   ┆          ┆ cat       ┆           ┆           │
│            ┆ 2]         ┆        ┆            ┆   ┆          ┆           ┆           ┆           │
╞════════════╪════════════╪════════╪════════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ 0          ┆ [-87.88570 ┆ 2.0    ┆ :263785883 ┆ … ┆ false    ┆ node_2637 ┆ -87.88570 ┆ 41.994915 │
│            ┆ 6,         ┆        ┆ _1_0       ┆   ┆          ┆ 85883     ┆ 6         ┆           │
│            ┆ 41.994915] ┆        ┆            ┆   ┆          ┆           ┆           ┆           │
│ 0          ┆ [-87.88572 ┆ 2.5    ┆ :263785883 ┆ … ┆ false    ┆ node_2637 ┆ -87.88572 ┆ 41.9949   │
│            ┆ 5,         ┆        ┆ _1_0       ┆   ┆          ┆ 85883     ┆ 5         ┆           │
│            ┆ 41.9949]   ┆        ┆            ┆   ┆          ┆           ┆           ┆           │
│ 0          ┆ [-87.88574 ┆ 3.0    ┆ :263785883 ┆ … ┆ false    ┆ node_2637 ┆ -87.88574 ┆ 41.994882 │
│            ┆ 8,         ┆        ┆ _1_0       ┆   ┆          ┆ 85883     ┆ 8         ┆           │
│            ┆ 41.994882] ┆        ┆            ┆   ┆          ┆           ┆           ┆           │
│ 0          ┆ [-87.88577 ┆ 3.5    ┆ :263785883 ┆ … ┆ false    ┆ node_2637 ┆ -87.88577 ┆ 41.994857 │
│            ┆ 1,         ┆        ┆ _1_0       ┆   ┆          ┆ 85883     ┆ 1         ┆           │
│            ┆ 41.994857] ┆        ┆            ┆   ┆          ┆           ┆           ┆           │
│ 0          ┆ [-87.88578 ┆ 4.0    ┆ :263785883 ┆ … ┆ false    ┆ node_2637 ┆ -87.88578 ┆ 41.994827 │
│            ┆ 9,         ┆        ┆ _1_0       ┆   ┆          ┆ 85883     ┆ 9         ┆           │
│            ┆ 41.994827] ┆        ┆            ┆   ┆          ┆           ┆           ┆           │
│ …          ┆ …          ┆ …      ┆ …          ┆ … ┆ …        ┆ …         ┆ …         ┆ …         │
│ 1702       ┆ [-87.88870 ┆ 4070.0 ┆ :135081252 ┆ … ┆ false    ┆ node_1350 ┆ -87.88870 ┆ 41.999024 │
│            ┆ 8,         ┆        ┆ 1_6_0      ┆   ┆          ┆ 812521    ┆ 8         ┆           │
│            ┆ 41.999024] ┆        ┆            ┆   ┆          ┆           ┆           ┆           │
│ 1702       ┆ [-87.88875 ┆ 4075.0 ┆ :100243435 ┆ … ┆ false    ┆ node_1002 ┆ -87.88875 ┆ 41.998723 │
│            ┆ 6,         ┆        ┆ 59_0_0     ┆   ┆          ┆ 4343559   ┆ 6         ┆           │
│            ┆ 41.998723] ┆        ┆            ┆   ┆          ┆           ┆           ┆           │
│ 1702       ┆ [-87.88872 ┆ 4075.5 ┆ :100243435 ┆ … ┆ false    ┆ node_1002 ┆ -87.88872 ┆ 41.998676 │
│            ┆ 3,         ┆        ┆ 59_0_0     ┆   ┆          ┆ 4343559   ┆ 3         ┆           │
│            ┆ 41.998676] ┆        ┆            ┆   ┆          ┆           ┆           ┆           │
│ 1702       ┆ [-87.88871 ┆ 4081.0 ┆ :100213037 ┆ … ┆ false    ┆ node_1002 ┆ -87.88871 ┆ 41.998089 │
│            ┆ 8,         ┆        ┆ 14_0_0     ┆   ┆          ┆ 1303714   ┆ 8         ┆           │
│            ┆ 41.998089] ┆        ┆            ┆   ┆          ┆           ┆           ┆           │
│ 1702       ┆ [-87.88874 ┆ 4081.5 ┆ :100213037 ┆ … ┆ false    ┆ node_1002 ┆ -87.88874 ┆ 41.998041 │
│            ┆ 9,         ┆        ┆ 14_0_0     ┆   ┆          ┆ 1303714   ┆ 9         ┆           │
│            ┆ 41.998041] ┆        ┆            ┆   ┆          ┆           ┆           ┆           │
└────────────┴────────────┴────────┴────────────┴───┴──────────┴───────────┴───────────┴───────────┘

In [32]:
from typing import cast

import pandas as pd


indexed_osm_edges = edges_gdf.reset_index().set_index("osmid")

node_df = df.filter(pl.col("node_mapped_id").cat.starts_with("node_"))

# pairs: set[tuple[int, int]] = set()

# for row in node_df.iter_rows(named=True):
#     next_id = row.get("edge_id")
#     if next_id is None:
#         continue
#     next_id = int(next_id)

#     node_mapped_id = row.get("node_mapped_id")
#     if node_mapped_id is None:
#         continue

#     node_mapped_id = row.get("node_mapped_id")
#     if node_mapped_id is None:
#         print(f"Skipping row with missing node_mapped_id: {row}")
#         continue

#     # node_mapped_id can be like "node_1234" or already an int/np.int64
#     if isinstance(node_mapped_id, str) and node_mapped_id.startswith("node_"):
#         node_mapped_id = int(node_mapped_id.replace("node_", ""))
#     else:
#         node_mapped_id = int(node_mapped_id)


dfs_to_add = []
for row in node_df.iter_rows(named=True):
    # skip rows without an edge_id
    next_id = row.get("edge_id")
    if next_id is None:
        # edge_id is unmapped for this row; skip it
        # optionally you can log or collect these rows for inspection
        print(f"Skipping row with missing edge_id: {row["raw_lane_id"]}")
        continue

    # ensure next_id is an int (handles numpy int types as well)
    next_id = int(next_id)

    node_mapped_id = row.get("node_mapped_id")
    if node_mapped_id is None:
        print(f"Skipping row with missing node_mapped_id: {row}")
        continue

    # node_mapped_id can be like "node_1234" or already an int/np.int64
    if isinstance(node_mapped_id, str) and node_mapped_id.startswith("node_"):
        node_mapped_id = int(node_mapped_id.replace("node_", ""))
    else:
        node_mapped_id = int(node_mapped_id)

    try:
        sel = indexed_osm_edges.loc[next_id, ["u", "v"]]  # type: ignore
        if isinstance(sel, (pd.Series,)):
            sel_df = sel.to_frame().T
        else:
            sel_df = sel
        edge = sel_df.values.tolist()
        if len(edge) == 0:
            print(f"No edge found for node {next_id}")
            continue

        if node_mapped_id and all((node_mapped_id not in e) for e in edge):
            # if u != node_mapped_id and node_mapped_id :
            neighbors = G.neighbors(node_mapped_id)
            
            u, v = next(((u, v) for u, v in edge if u in neighbors), edge[0])

            connect_edges = ensure_connection(G, node_mapped_id, u)
            if connect_edges:
                # insert new edges into df
                new_row = row.copy()
                del new_row["edge_id"]
                del new_row["time"]

                new_df = pl.DataFrame(
                    [
                        {
                            **new_row,
                            "edge_id": str(connect_edge),
                            "time": float(row["time"] + (i * 0.01)),
                        }
                        for i, connect_edge in enumerate(connect_edges)
                    ]
                )
                new_df = new_df.with_columns(
                    pl.col("time").cast(pl.Float64),
                    pl.col("raw_lane_id").cast(pl.Categorical),
                    pl.col("vehicle_id").cast(pl.Int64),
                    pl.col("geo_position").cast(pl.Array(pl.Float64, shape=2)),
                    pl.col("edge_id").cast(pl.Categorical),
                    pl.col("node_mapped_id").cast(pl.Categorical),
                    pl.col("mapped_lane_id").cast(pl.Categorical),
                )
                dfs_to_add.append(new_df)
                df = df.remove(pl.col("raw_lane_id") == row["raw_lane_id"])  # type: ignore

    except KeyError:
        print(f"KeyError: {node_mapped_id}")

Skipping row with missing edge_id: :12793948413_0_0
Skipping row with missing edge_id: :12793948413_0_0
Skipping row with missing edge_id: :12793948413_0_0
Skipping row with missing edge_id: :310333211_0_0
Skipping row with missing edge_id: :310333211_0_0
Skipping row with missing edge_id: :310333211_0_0
Skipping row with missing edge_id: :6378331511_0_0
Skipping row with missing edge_id: :311482791_1_0
Skipping row with missing edge_id: :311482791_1_0
Skipping row with missing edge_id: :311482791_1_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :11038570643_0_0
Skipping row with missing edge_id: :11038570643_0_0
Skipping row with missing edge_id: :12793948413_0_0
Skipping row with missing edge_id: :12793948413_0_0
Skipping row with missing edge_id: :12793948413_0_0
Skipping row with missing edge_id: :12793878899_2_0
Skipping row with missing edge_id: :12793878899_2_0
Skipping row with missing edge_id: :11190389927_1_0
Skipping row with missing edge_id: :310333648_0_0
Skipping row with missing edge_id: :310333648_0_0
Skipping row with missing edge_id: :310333648_0_0
Skipping row with missing edge_id: :310333648_0_0
Skipping row with missing edge_id: :12085592684_0_0
Skipping row with missing edge_id: :310333172_2_0
Skipping row with missing edge_id: :310333172_2_0
Skipping row with missing edge_id: :310333211_0_0
Skipping row with missing edge_id: :310333211_0_0
Skipping row with missing edge_id: :310333648_0_0
Skipping row with missing edge_id: :310333648_0_0
Skipping row with missing edge_id: :310333648_0_0
Skipping row with missing edge_id: :12085592684_0_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :310333648_0_0
Skipping row with missing edge_id: :310333648_0_0
Skipping row with missing edge_id: :310333648_0_0
Skipping row with missing edge_id: :310333648_0_0
Skipping row with missing edge_id: :310333648_0_0
Skipping row with missing edge_id: :310333648_0_0
Skipping row with missing edge_id: :310333648_0_0
Skipping row with missing edge_id: :310333172_2_0
Skipping row with missing edge_id: :310333172_2_0
Skipping row with missing edge_id: :2610439065_2_0
Skipping row with missing edge_id: :2610439065_2_0
Skipping row with missing edge_id: :2610439065_2_0
Skipping row with missing edge_id: :310333172_2_0
Skipping row with missing edge_id: :310333172_2_0
Skipping row with missing edge_id: :12793878900_2_0
Skipping row with missing edge_id: :311482791_1_0
Skipping row with missing edge_id: :311482791_1_0
Skipping row with missing edge_id: :311482791_1_0
Skipping row with missing edge_id: :311482791_1_0
Skipping row with missing edge_id: :311482791_1_0
Skipping row with missing edge_id: :311482791_1_0
Skipping row with missing edge_id: :311482791_1_0
Skipping row with missing edge_id: :311482791_1_0
Skipping row with missing edge_id: :311482791_1_0
Skipping row with missing edge_id: :311482791_1_0
Skipping row with missing edge_id: :311482791_1_0
Skipping row with missing edge_id: :311482791_1_0
Skipping row with missing edge_id: :311482791_1_0
Skipping row with missing edge_id: :311482791_1_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :12793948413_0_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :12793948413_0_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :12793948413_0_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :263785875_5_0
Skipping row with missing edge_id: :263785875_5_0
Skipping row with missing edge_id: :263785875_5_0
Skipping row with missing edge_id: :263785875_5_0
Skipping row with missing edge_id: :2610439065_5_0
Skipping row with missing edge_id: :2610439065_5_0
Skipping row with missing edge_id: :2610439065_5_0
Skipping row with missing edge_id: :310333172_2_0
Skipping row with missing edge_id: :310333172_2_0
Skipping row with missing edge_id: :310333172_2_0
Skipping row with missing edge_id: :310333211_0_0
Skipping row with missing edge_id: :310333211_0_0
Skipping row with missing edge_id: :12085592684_0_0
Skipping row with missing edge_id: :310333648_0_0
Skipping row with missing edge_id: :310333648_0_0
Skipping row with missing edge_id: :310333648_0_0
Skipping row with missing edge_id: :310333648_0_0
Skipping row with missing edge_id: :310333648_0_0
Skipping row with missing edge_id: :310333648_0_0
Skipping row with missing edge_id: :310333648_0_0
Skipping row with missing edge_id: :310333648_0_0
Skipping row with missing edge_id: :310333648_0_0
Skipping row with missing edge_id: :310333648_0_0
Skipping row with missing edge_id: :310333648_0_0
Skipping row with missing edge_id: :310333648_0_0
Skipping row with missing edge_id: :310333648_0_0
Skipping row with missing edge_id: :12085592684_0_0
Skipping row with missing edge_id: :310333648_0_0
Skipping row with missing edge_id: :12085592683_0_0
Skipping row with missing edge_id: :310333648_0_0
Skipping row with missing edge_id: :12085592683_0_0
Skipping row with missing edge_id: :310333648_0_0
Skipping row with missing edge_id: :310333648_0_0
Skipping row with missing edge_id: :310333648_0_0
Skipping row with missing edge_id: :12793948403_2_0
Skipping row with missing edge_id: :12793948403_2_0
Skipping row with missing edge_id: :12793948403_2_0
Skipping row with missing edge_id: :12793948403_2_0
Skipping row with missing edge_id: :12793948403_2_0
Skipping row with missing edge_id: :12793948403_2_0
Skipping row with missing edge_id: :11190389927_1_0
Skipping row with missing edge_id: :2610439065_2_0
Skipping row with missing edge_id: :2610439065_2_0
Skipping row with missing edge_id: :2610439065_2_0
Skipping row with missing edge_id: :12085592684_0_0
Skipping row with missing edge_id: :12085592684_0_0
Skipping row with missing edge_id: :12793948413_0_0
Skipping row with missing edge_id: :12793948413_0_0
Skipping row with missing edge_id: :12793948413_0_0
Skipping row with missing edge_id: :12793948403_2_0
Skipping row with missing edge_id: :12793948403_2_0
Skipping row with missing edge_id: :12793948403_2_0
Skipping row with missing edge_id: :310333211_0_0
Skipping row with missing edge_id: :310333211_0_0
Skipping row with missing edge_id: :263785875_1_0
Skipping row with missing edge_id: :311482791_4_0
Skipping row with missing edge_id: :311482791_4_0
Skipping row with missing edge_id: :311482791_4_0
Skipping row with missing edge_id: :311482791_4_0
Skipping row with missing edge_id: :311482791_4_0
Skipping row with missing edge_id: :311482791_4_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :12793948403_2_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :12793948403_2_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :12793948403_2_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :310333172_2_0
Skipping row with missing edge_id: :310333172_2_0
Skipping row with missing edge_id: :12793878900_2_0
Skipping row with missing edge_id: :310333211_0_0
Skipping row with missing edge_id: :310333211_0_0
Skipping row with missing edge_id: :12793948413_0_0
Skipping row with missing edge_id: :12793948413_0_0
Skipping row with missing edge_id: :12793948413_0_0
Skipping row with missing edge_id: :311482827_0_0
Skipping row with missing edge_id: :311482827_0_0
Skipping row with missing edge_id: :311482827_0_0
Skipping row with missing edge_id: :311482827_0_0
Skipping row with missing edge_id: :263785875_5_0
Skipping row with missing edge_id: :263785875_5_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :263785875_5_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :263785875_5_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :2610439065_5_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :2610439065_5_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :2610439065_5_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :263785875_5_0
Skipping row with missing edge_id: :263785875_5_0
Skipping row with missing edge_id: :263785875_5_0
Skipping row with missing edge_id: :2610439065_2_0
Skipping row with missing edge_id: :2610439065_2_0
Skipping row with missing edge_id: :2610439065_2_0
Skipping row with missing edge_id: :2610439065_2_0
Skipping row with missing edge_id: :311482791_4_0
Skipping row with missing edge_id: :311482791_4_0
Skipping row with missing edge_id: :311482791_4_0
Skipping row with missing edge_id: :311482791_4_0
Skipping row with missing edge_id: :310333211_0_0
Skipping row with missing edge_id: :310333211_0_0
Skipping row with missing edge_id: :6378331511_0_0
Skipping row with missing edge_id: :310333211_0_0
Skipping row with missing edge_id: :310333211_0_0
Skipping row with missing edge_id: :310333211_0_0
Skipping row with missing edge_id: :310333648_0_0
Skipping row with missing edge_id: :310333648_0_0
Skipping row with missing edge_id: :310333648_0_0
Skipping row with missing edge_id: :310333648_0_0
Skipping row with missing edge_id: :2610439065_2_0
Skipping row with missing edge_id: :2610439065_2_0
Skipping row with missing edge_id: :2610439065_2_0
Skipping row with missing edge_id: :2610439065_2_0
Skipping row with missing edge_id: :2610439065_2_0
Skipping row with missing edge_id: :2610439065_2_0
Skipping row with missing edge_id: :2610439065_5_0
Skipping row with missing edge_id: :2610439065_5_0
Skipping row with missing edge_id: :2610439065_5_0
Skipping row with missing edge_id: :311482791_4_0
Skipping row with missing edge_id: :311482791_4_0
Skipping row with missing edge_id: :311482791_4_0
Skipping row with missing edge_id: :311482791_4_0
Skipping row with missing edge_id: :310333648_0_0
Skipping row with missing edge_id: :310333648_0_0
Skipping row with missing edge_id: :310333648_0_0
Skipping row with missing edge_id: :310333648_0_0
Skipping row with missing edge_id: :310333648_0_0
Skipping row with missing edge_id: :310333648_0_0
Skipping row with missing edge_id: :310333648_0_0
Skipping row with missing edge_id: :6378331511_0_0
Skipping row with missing edge_id: :11190389927_1_0
Skipping row with missing edge_id: :11190389927_1_0
Skipping row with missing edge_id: :11190389927_1_0
Skipping row with missing edge_id: :11190389927_1_0
Skipping row with missing edge_id: :11190389927_1_0
Skipping row with missing edge_id: :11190389927_1_0
Skipping row with missing edge_id: :12793948413_0_0
Skipping row with missing edge_id: :12793948413_0_0
Skipping row with missing edge_id: :12793948413_0_0
Skipping row with missing edge_id: :310333211_0_0
Skipping row with missing edge_id: :310333211_0_0
Skipping row with missing edge_id: :2610439065_2_0
Skipping row with missing edge_id: :2610439065_2_0
Skipping row with missing edge_id: :2610439065_2_0
Skipping row with missing edge_id: :2610439065_2_0
Skipping row with missing edge_id: :311482791_4_0
Skipping row with missing edge_id: :311482791_4_0
Skipping row with missing edge_id: :311482791_4_0
Skipping row with missing edge_id: :311482791_4_0
Skipping row with missing edge_id: :2610439065_5_0
Skipping row with missing edge_id: :2610439065_5_0
Skipping row with missing edge_id: :2610439065_5_0
Skipping row with missing edge_id: :2610439065_5_0
Skipping row with missing edge_id: :2610439065_5_0
Skipping row with missing edge_id: :2610439065_5_0
Skipping row with missing edge_id: :2610439065_5_0
Skipping row with missing edge_id: :2610439065_5_0
Skipping row with missing edge_id: :2610439065_5_0
Skipping row with missing edge_id: :2610439065_5_0
Skipping row with missing edge_id: :2610439065_5_0
Skipping row with missing edge_id: :2610439065_5_0
Skipping row with missing edge_id: :2610439065_5_0
Skipping row with missing edge_id: :2610439065_5_0
Skipping row with missing edge_id: :2610439065_5_0
Skipping row with missing edge_id: :2610439065_5_0
Skipping row with missing edge_id: :2610439065_5_0
Skipping row with missing edge_id: :2610439065_5_0
Skipping row with missing edge_id: :2610439065_5_0
Skipping row with missing edge_id: :2610439065_5_0
Skipping row with missing edge_id: :2610439065_5_0
Skipping row with missing edge_id: :2610439065_5_0
Skipping row with missing edge_id: :2610439065_5_0
Skipping row with missing edge_id: :2610439065_5_0
Skipping row with missing edge_id: :2610439065_5_0
Skipping row with missing edge_id: :2610439065_5_0
Skipping row with missing edge_id: :2610439065_5_0
Skipping row with missing edge_id: :2610439065_5_0
Skipping row with missing edge_id: :2610439065_5_0
Skipping row with missing edge_id: :2610439065_5_0
Skipping row with missing edge_id: :2610439065_5_0
Skipping row with missing edge_id: :2610439065_5_0
Skipping row with missing edge_id: :2610439065_5_0
Skipping row with missing edge_id: :2610439065_5_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :12793948403_2_0
Skipping row with missing edge_id: :12793948403_2_0
Skipping row with missing edge_id: :12793948403_2_0
Skipping row with missing edge_id: :12793948403_2_0
Skipping row with missing edge_id: :12793948403_2_0
Skipping row with missing edge_id: :12793948403_2_0
Skipping row with missing edge_id: :12793878899_2_0
Skipping row with missing edge_id: :12793878899_2_0
Skipping row with missing edge_id: :12793878900_2_0
Skipping row with missing edge_id: :310333211_0_0
Skipping row with missing edge_id: :310333211_0_0
Skipping row with missing edge_id: :310333211_0_0
Skipping row with missing edge_id: :6378331511_0_0
Skipping row with missing edge_id: :2610439065_2_0
Skipping row with missing edge_id: :2610439065_2_0
Skipping row with missing edge_id: :2610439065_2_0
Skipping row with missing edge_id: :2610439065_2_0
Skipping row with missing edge_id: :2610439065_2_0
Skipping row with missing edge_id: :2610439065_2_0
Skipping row with missing edge_id: :2610439065_2_0
Skipping row with missing edge_id: :311482791_4_0
Skipping row with missing edge_id: :311482791_4_0
Skipping row with missing edge_id: :311482791_4_0
Skipping row with missing edge_id: :311482791_4_0
Skipping row with missing edge_id: :311482791_4_0
Skipping row with missing edge_id: :311482791_4_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :311482791_1_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :311482791_1_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :311482791_1_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :311482791_1_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :311482791_1_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :311482791_1_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :311482791_1_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :311482791_1_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :263785875_5_0
Skipping row with missing edge_id: :263785875_5_0
Skipping row with missing edge_id: :263785875_5_0
Skipping row with missing edge_id: :263785875_5_0
Skipping row with missing edge_id: :12793878899_2_0
Skipping row with missing edge_id: :12793878899_2_0
Skipping row with missing edge_id: :2610439065_2_0
Skipping row with missing edge_id: :2610439065_2_0
Skipping row with missing edge_id: :2610439065_2_0
Skipping row with missing edge_id: :11190389927_1_0
Skipping row with missing edge_id: :11190389927_1_0
Skipping row with missing edge_id: :11190389927_1_0
Skipping row with missing edge_id: :12793878899_2_0
Skipping row with missing edge_id: :12793878899_2_0
Skipping row with missing edge_id: :12793878899_2_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :263785875_5_0
Skipping row with missing edge_id: :263785875_5_0
Skipping row with missing edge_id: :263785875_5_0
Skipping row with missing edge_id: :263785875_5_0
Skipping row with missing edge_id: :311482791_1_0
Skipping row with missing edge_id: :311482791_1_0
Skipping row with missing edge_id: :311482791_1_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :11190389927_1_0
Skipping row with missing edge_id: :11190389927_1_0
Skipping row with missing edge_id: :311482791_1_0
Skipping row with missing edge_id: :311482791_1_0
Skipping row with missing edge_id: :311482791_1_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :263785875_5_0
Skipping row with missing edge_id: :263785875_5_0
Skipping row with missing edge_id: :263785875_5_0
Skipping row with missing edge_id: :263785875_5_0
Skipping row with missing edge_id: :2610439065_5_0
Skipping row with missing edge_id: :2610439065_5_0
Skipping row with missing edge_id: :2610439065_5_0
Skipping row with missing edge_id: :2610439065_5_0
Skipping row with missing edge_id: :12793948413_0_0
Skipping row with missing edge_id: :12793948413_0_0
Skipping row with missing edge_id: :12793948413_0_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :311482827_1_0
Skipping row with missing edge_id: :12793948403_2_0
Skipping row with missing edge_id: :12793948403_2_0
Skipping row with missing edge_id: :12793948403_2_0
Skipping row with missing edge_id: :310333172_2_0
Skipping row with missing edge_id: :310333172_2_0
Skipping row with missing edge_id: :310333172_2_0
Skipping row with missing edge_id: :12793948413_0_0
Skipping row with missing edge_id: :12793948413_0_0
Skipping row with missing edge_id: :12793878899_2_0
Skipping row with missing edge_id: :12793878899_2_0
Skipping row with missing edge_id: :310333648_0_0
Skipping row with missing edge_id: :310333648_0_0
Skipping row with missing edge_id: :310333648_0_0

In [41]:
df_to_add = pl.DataFrame(
        {
            "time": pl.Int64,
            "vehicle_id": pl.Int64,
            "geo_position": pl.Array(pl.Float64, shape=2),
            "edge_id": pl.Categorical,
            "mapped_lane_id": pl.Categorical,
            "node_mapped_id": pl.Categorical,
            "raw_lane_id": pl.Categorical,
        }
    )

if dfs_to_add:
    df_to_add = pl.concat(dfs_to_add)
    df_to_add = df_to_add.with_columns(
        pl.col("time").cast(pl.Float64),
        pl.col("vehicle_id").cast(pl.Int64),
        pl.col("geo_position").cast(pl.Array(pl.Float64, shape=2)),
        
        pl.col("edge_id").cast(pl.Categorical),
        pl.col("mapped_lane_id").cast(pl.Categorical),
        pl.col("node_mapped_id").cast(pl.Categorical),
        pl.col("raw_lane_id").cast(pl.Categorical),
    )

In [42]:
df_to_add.describe()

shape: (9, 11)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬─────────┬───────────┐
│ statistic  ┆ vehicle_i ┆ geo_posit ┆ raw_lane_ ┆ … ┆ lon       ┆ lat       ┆ edge_id ┆ time      │
│ ---        ┆ d         ┆ ion       ┆ id        ┆   ┆ ---       ┆ ---       ┆ ---     ┆ ---       │
│ str        ┆ ---       ┆ ---       ┆ ---       ┆   ┆ f64       ┆ f64       ┆ str     ┆ f64       │
│            ┆ f64       ┆ f64       ┆ str       ┆   ┆           ┆           ┆         ┆           │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═════════╪═══════════╡
│ count      ┆ 25596.0   ┆ 25596.0   ┆ 25596     ┆ … ┆ 25596.0   ┆ 25596.0   ┆ 25596   ┆ 25596.0   │
│ null_count ┆ 0.0       ┆ 0.0       ┆ 0         ┆ … ┆ 0.0       ┆ 0.0       ┆ 0       ┆ 0.0       │
│ mean       ┆ 907.87697 ┆ null      ┆ null      ┆ … ┆ -87.88967 ┆ 41.983587 ┆ null    ┆ 2021.6854 │
│            ┆ 3         ┆           ┆           ┆   ┆ 3         ┆           ┆         ┆ 22        │
│ std        ┆ 509.92266 ┆ null      ┆ null      ┆ … ┆ 0.006882  ┆ 0.006597  ┆ null    ┆ 1037.7834 │
│            ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆         ┆ 19        │
│ min        ┆ 2.0       ┆ null      ┆ null      ┆ … ┆ -87.90596 ┆ 41.976659 ┆ null    ┆ 40.5      │
│            ┆           ┆           ┆           ┆   ┆ 5         ┆           ┆         ┆           │
│ 25%        ┆ 493.0     ┆ null      ┆ null      ┆ … ┆ -87.89910 ┆ 41.979059 ┆ null    ┆ 1167.0    │
│            ┆           ┆           ┆           ┆   ┆ 9         ┆           ┆         ┆           │
│ 50%        ┆ 927.0     ┆ null      ┆ null      ┆ … ┆ -87.88578 ┆ 41.980161 ┆ null    ┆ 2023.0    │
│            ┆           ┆           ┆           ┆   ┆ 4         ┆           ┆         ┆           │
│ 75%        ┆ 1368.0    ┆ null      ┆ null      ┆ … ┆ -87.88560 ┆ 41.990362 ┆ null    ┆ 2947.02   │
│            ┆           ┆           ┆           ┆   ┆ 5         ┆           ┆         ┆           │
│ max        ┆ 1758.0    ┆ null      ┆ null      ┆ … ┆ -87.87907 ┆ 41.995177 ┆ null    ┆ 3999.0    │
│            ┆           ┆           ┆           ┆   ┆ 8         ┆           ┆         ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴─────────┴───────────┘

In [43]:
df_to_add = df_to_add.select(df.columns)

concated_df = pl.concat([df, df_to_add], how="vertical")
concated_df = concated_df.sort(["time", "vehicle_id"])
concated_df

shape: (868_421, 10)
┌────────────┬────────────┬────────┬────────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ vehicle_id ┆ geo_positi ┆ time   ┆ raw_lane_i ┆ … ┆ reversed ┆ node_mapp ┆ lon       ┆ lat       │
│ ---        ┆ on         ┆ ---    ┆ d          ┆   ┆ ---      ┆ ed_id     ┆ ---       ┆ ---       │
│ i64        ┆ ---        ┆ f64    ┆ ---        ┆   ┆ bool     ┆ ---       ┆ f64       ┆ f64       │
│            ┆ array[f64, ┆        ┆ cat        ┆   ┆          ┆ cat       ┆           ┆           │
│            ┆ 2]         ┆        ┆            ┆   ┆          ┆           ┆           ┆           │
╞════════════╪════════════╪════════╪════════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ 0          ┆ [-87.88567 ┆ 0.5    ┆ 1188647984 ┆ … ┆ false    ┆ 118864798 ┆ -87.88567 ┆ 41.994941 │
│            ┆ 1,         ┆        ┆ _0         ┆   ┆          ┆ 4         ┆ 1         ┆           │
│            ┆ 41.994941] ┆        ┆            ┆   ┆          ┆           ┆           ┆           │
│ 0          ┆ [-87.88567 ┆ 1.0    ┆ 1188647984 ┆ … ┆ false    ┆ 118864798 ┆ -87.88567 ┆ 41.994936 │
│            ┆ 7,         ┆        ┆ _0         ┆   ┆          ┆ 4         ┆ 7         ┆           │
│            ┆ 41.994936] ┆        ┆            ┆   ┆          ┆           ┆           ┆           │
│ 0          ┆ [-87.88568 ┆ 1.5    ┆ 1188647984 ┆ … ┆ false    ┆ 118864798 ┆ -87.88568 ┆ 41.994928 │
│            ┆ 9,         ┆        ┆ _0         ┆   ┆          ┆ 4         ┆ 9         ┆           │
│            ┆ 41.994928] ┆        ┆            ┆   ┆          ┆           ┆           ┆           │
│ 0          ┆ [-87.88570 ┆ 2.0    ┆ :263785883 ┆ … ┆ false    ┆ node_2637 ┆ -87.88570 ┆ 41.994915 │
│            ┆ 6,         ┆        ┆ _1_0       ┆   ┆          ┆ 85883     ┆ 6         ┆           │
│            ┆ 41.994915] ┆        ┆            ┆   ┆          ┆           ┆           ┆           │
│ 0          ┆ [-87.88572 ┆ 2.5    ┆ :263785883 ┆ … ┆ false    ┆ node_2637 ┆ -87.88572 ┆ 41.9949   │
│            ┆ 5,         ┆        ┆ _1_0       ┆   ┆          ┆ 85883     ┆ 5         ┆           │
│            ┆ 41.9949]   ┆        ┆            ┆   ┆          ┆           ┆           ┆           │
│ …          ┆ …          ┆ …      ┆ …          ┆ … ┆ …        ┆ …         ┆ …         ┆ …         │
│ 1702       ┆ [-87.88874 ┆ 4081.5 ┆ :100213037 ┆ … ┆ false    ┆ node_1002 ┆ -87.88874 ┆ 41.998041 │
│            ┆ 9,         ┆        ┆ 14_0_0     ┆   ┆          ┆ 1303714   ┆ 9         ┆           │
│            ┆ 41.998041] ┆        ┆            ┆   ┆          ┆           ┆           ┆           │
│ 1702       ┆ [-87.88875 ┆ 4082.0 ┆ 1094214001 ┆ … ┆ false    ┆ 109421400 ┆ -87.88875 ┆ 41.997985 │
│            ┆ 6,         ┆        ┆ _0         ┆   ┆          ┆ 1         ┆ 6         ┆           │
│            ┆ 41.997985] ┆        ┆            ┆   ┆          ┆           ┆           ┆           │
│ 1702       ┆ [-87.88875 ┆ 4082.5 ┆ 1094214001 ┆ … ┆ false    ┆ 109421400 ┆ -87.88875 ┆ 41.997933 │
│            ┆ 6,         ┆        ┆ _0         ┆   ┆          ┆ 1         ┆ 6         ┆           │
│            ┆ 41.997933] ┆        ┆            ┆   ┆          ┆           ┆           ┆           │
│ 1702       ┆ [-87.88875 ┆ 4083.0 ┆ 1094214001 ┆ … ┆ false    ┆ 109421400 ┆ -87.88875 ┆ 41.997881 │
│            ┆ 7,         ┆        ┆ _0         ┆   ┆          ┆ 1         ┆ 7         ┆           │
│            ┆ 41.997881] ┆        ┆            ┆   ┆          ┆           ┆           ┆           │
│ 1702       ┆ [-87.88875 ┆ 4083.5 ┆ 1094214001 ┆ … ┆ false    ┆ 109421400 ┆ -87.88875 ┆ 41.997827 │
│            ┆ 7,         ┆        ┆ _0         ┆   ┆          ┆ 1         ┆ 7         ┆           │
│            ┆ 41.997827] ┆        ┆            ┆   ┆          ┆           ┆           ┆           │
└────────────┴────────────┴────────┴────────────┴───┴──────────┴───────────┴───────────┴───────────┘

In [44]:
c = concated_df.filter(pl.col("vehicle_id") == 1001).to_pandas().sort_values(["vehicle_id", "time"])
c

,vehicle_id,geo_position,time,raw_lane_id,mapped_lane_id,edge_id,reversed,node_mapped_id,lon,lat
0,1001,"[-87.88580060152805, 41.97764234868195]",2092.0,1238156320_0,1238156320_0,1238156320,False,1238156320,-87.885801,41.977642
1,1001,"[-87.88576324022672, 41.97763372198496]",2092.5,1238156320_1,1238156320_1,1238156320,False,1238156320,-87.885763,41.977634
2,1001,"[-87.88572655353623, 41.977620687177506]",2093.0,1238156320_2,1238156320_2,1238156320,False,1238156320,-87.885727,41.977621
3,1001,"[-87.88572877714086, 41.977608018398676]",2093.5,1238156320_2,1238156320_2,1238156320,False,1238156320,-87.885729,41.977608
4,1001,"[-87.88573159751046, 41.97759194960051]",2094.0,1238156320_2,1238156320_2,1238156320,False,1238156320,-87.885732,41.977592
...,...,...,...,...,...,...,...,...,...,...
594,1001,"[-87.8887181048239, 41.998918873263484]",2387.5,1094498007_1,1094498007_1,1094498007,False,1094498007,-87.888718,41.998919
595,1001,"[-87.88872077008891, 41.99888294985146]",2388.0,1094498007_1,1094498007_1,1094498007,False,1094498007,-87.888721,41.998883
596,1001,"[-87.88872216880448, 41.99884171195431]",2388.5,1094498007_1,1094498007_1,1094498007,False,1094498007,-87.888722,41.998842
597,1001,"[-87.88872193244057, 41.9987950823738]",2389.0,1094498007_1,1094498007_1,1094498007,False,1094498007,-87.888722,41.998795
598,1001,"[-87.88872167373789, 41.99874404561623]",2389.5,1094498007_1,1094498007_1,1094498007,False,1094498007,-87.888722,41.998744

In [45]:
concated_df.write_parquet(DATASET_PATH.with_name("fcd_resolved.parquet"), compression="zstd")

In [46]:

lf2 = lf.with_columns(
    pl.col("mapped_lane_id").cast(pl.String)
    .str.extract(r"(-?\d+)(?:.*)", 1)
    .alias("edge_id")
)

lf2 = lf2.with_columns(
    pl.col("edge_id").str.starts_with("-").alias("reversed"),
    pl.col("edge_id").str.replace("-", ""),
)

is_node = pl.col("edge_id").cast(pl.Int64).is_in(G.nodes())

lf2 = lf2.with_columns(
    pl.when(is_node)
    .then(pl.lit("node_") + pl.col("edge_id"))
    .otherwise(pl.col("edge_id"))
    .alias("edge_id")
)

lf2 = lf2.with_columns(
    pl.col("raw_lane_id").cast(pl.Categorical),
    pl.col("mapped_lane_id").cast(pl.Categorical),
    pl.col("edge_id").cast(pl.Categorical)
)

lf2 = lf2.with_columns(
    pl.col("edge_id").alias("node_mapped_id")
)

lf2 = lf2.with_columns(
    pl.when(~pl.col("edge_id").cat.starts_with("node_"))
    .then(pl.col("edge_id"))
    .otherwise(None)
    .alias("edge_id_valid")
)

lf2 = lf2.with_columns(
    pl.col("edge_id_valid")
    .backward_fill()
    .over("vehicle_id")
    .alias("edge_id")
)

lf2.sort(["vehicle_id", "time"])

df2 = lf2.collect()
pd_df2 = df2.to_pandas().sort_values(["vehicle_id", "time"])
pd_df2

,vehicle_id,geo_position,time,raw_lane_id,mapped_lane_id,edge_id,reversed,node_mapped_id,lon,lat,edge_id_valid
0,0,"[-87.8856713296918, 41.99494072305388]",0.5,1188647984_0,1188647984_0,1188647984,False,1188647984,-87.885671,41.994941,1188647984
1,0,"[-87.88567733180858, 41.994936271618215]",1.0,1188647984_0,1188647984_0,1188647984,False,1188647984,-87.885677,41.994936,1188647984
2,0,"[-87.88568911243644, 41.994927534580114]",1.5,1188647984_0,1188647984_0,1188647984,False,1188647984,-87.885689,41.994928,1188647984
3,0,"[-87.88570568973026, 41.99491498626672]",2.0,:263785883_1_0,:263785883_1_0,321574768,False,node_263785883,-87.885706,41.994915,NaN
4,0,"[-87.88572492532072, 41.994900100759565]",2.5,:263785883_1_0,:263785883_1_0,321574768,False,node_263785883,-87.885725,41.994900,NaN
...,...,...,...,...,...,...,...,...,...,...,...
849776,1758,"[-87.88204500820018, 41.98479676583491]",3760.5,-4685903_0,-4685903_0,4685903,True,4685903,-87.882045,41.984797,4685903
849830,1758,"[-87.8819512028677, 41.98479704745202]",3761.0,-4685903_0,-4685903_0,4685903,True,4685903,-87.881951,41.984797,4685903
849884,1758,"[-87.88185635890108, 41.98479733210934]",3761.5,-4685903_0,-4685903_0,4685903,True,4685903,-87.881856,41.984797,4685903
849938,1758,"[-87.88176341113001, 41.98478515335567]",3762.0,-4685903_0,-4685903_0,4685903,True,4685903,-87.881763,41.984785,4685903
849992,1758,"[-87.88168607892295, 41.98474808290379]",3762.5,-4685903_0,-4685903_0,4685903,True,4685903,-87.881686,41.984748,4685903

In [47]:
[(u, v) for u, v, data in G.edges(data=True) if data.get("osmid") == 474730115]

[(7710696746, 4686227120),
 (8872546867, 10970085837),
 (10970085837, 10970085838),
 (10970085838, 7710696746)]