In [134]:
import json
import requests
from pathlib import Path

import duckdb
import polyline
import pandas as pd

from geopy.distance import geodesic

from to_gpx import to_gpx

In [135]:
DATA_BASE_PATH = Path("./data").resolve().absolute()
GRAPHHOPPER_BASE_URL = "http://localhost:8989"
GPS_ACCURACY = 50

In [136]:
gps_data_path = DATA_BASE_PATH / "gps_data.parquet"
ground_truth_path = DATA_BASE_PATH / "ground_truth_route.parquet"
newson_krumm_route_network_path = DATA_BASE_PATH / "road_network.parquet"

In [137]:
ground_truth_df = duckdb.query(
    f"""
    WITH gt AS (
        SELECT edge_id, traversed, ROW_NUMBER() OVER () as row_num
        FROM '{ground_truth_path}'
    )
    SELECT gt.edge_id, traversed, linestring
    FROM gt
    LEFT JOIN '{newson_krumm_route_network_path}' nkr 
    ON gt.edge_id = nkr.edge_id
    ORDER BY gt.row_num
    """
).to_df()
ground_truth_df

,edge_id,traversed,linestring
0,884147800801,1,"LINESTRING(-122.109748721123 47.6673012971878,..."
1,884147800802,1,"LINESTRING(-122.105398178101 47.6675292849541,..."
2,884147800421,1,"LINESTRING(-122.102048099041 47.6676607131958,..."
3,884147800422,1,"LINESTRING(-122.1028393507 47.6681300997734, -..."
4,884147800423,1,"LINESTRING(-122.103689610958 47.6685512065887,..."
...,...,...,...
571,884147801154,1,"LINESTRING(-122.14302957058 47.6376816630363, ..."
572,884147800845,1,"LINESTRING(-122.14302957058 47.6378801465034, ..."
573,884147800842,1,"LINESTRING(-122.14291960001 47.6386311650276, ..."
574,884147800843,1,"LINESTRING(-122.142908871174 47.6404094696045,..."
575,884147800892,0,"LINESTRING(-122.141358554363 47.6413804292679,..."

In [138]:
route_network_df = duckdb.query(
    f"""
    SELECT edge_id, linestring 
    FROM '{newson_krumm_route_network_path}'
    """
).to_df()
route_network_df

             edge_id                                         linestring
0       883991900000  LINESTRING(-122.732318937778 47.8899192810059,...
1       883991900001  LINESTRING(-122.71107852459 47.8776508569717, ...
2       883991900002  LINESTRING(-122.707419991493 47.8761515021324,...
3       883991900003  LINESTRING(-122.707419991493 47.8761515021324,...
4       883991900004  LINESTRING(-122.715329825878 47.8818699717522,...
...              ...                                                ...
158162  884152400184  LINESTRING(-121.777908504009 47.4525502324104,...
158163  884152400185  LINESTRING(-121.781320273876 47.4532207846642,...
158164  884152400186  LINESTRING(-121.784308254719 47.4577805399895,...
158165  884152400187  LINESTRING(-121.782489717007 47.4503803253174,...
158166  884152400188  LINESTRING(-121.754589378834 47.4459412693977,...

[158167 rows x 2 columns]

In [139]:
def parse_linestring(linestring_series: pd.Series) -> pd.Series:
    track_segs = linestring_series.str.replace(r"^LINESTRING\(|\)$", "", regex=True)
    track_segs = track_segs.str.replace(",", ";").replace(r"\s+", " ", regex=True)
    track_segs = track_segs.str.split(";")
    track_segs = track_segs.apply(
        lambda x: [tuple((lat, lon)) for (lon, lat) in (point.split() for point in x)]
    )
    return track_segs

In [140]:
ground_truth_df["track_segs"] = parse_linestring(ground_truth_df["linestring"])
route_network_df["track_segs"] = parse_linestring(route_network_df["linestring"])

In [141]:
gps_df = duckdb.query(f"SELECT * FROM '{gps_data_path}'").to_df()
gps_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7531 entries, 0 to 7530
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   recorded_timestamp  7531 non-null   datetime64[us]
 1   lon                 7531 non-null   float64
 2   lat                 7531 non-null   float64
dtypes: datetime64[us](1), float64(2)
memory usage: 176.6 KB

In [142]:
gps_df.head()

   recorded_timestamp         lon        lat
0 2009-01-17 20:27:37 -122.107083  47.667483
1 2009-01-17 20:27:38 -122.107067  47.667500
2 2009-01-17 20:27:39 -122.107067  47.667500
3 2009-01-17 20:27:40 -122.107033  47.667517
4 2009-01-17 20:27:41 -122.106983  47.667533

In [143]:
points = gps_df[["lon", "lat", "recorded_timestamp"]].to_numpy()

gpx_path = to_gpx(points, DATA_BASE_PATH / "gps.gpx")

In [144]:
def request_map_matching(point_gpx_path: Path, output_path: Path) -> str:
    url = f"{GRAPHHOPPER_BASE_URL}/match?profile=car&gps_accuracy={GPS_ACCURACY}&type=json&locale=pt_BR&details=osm_way_id"
    headers = {
        "Content-Type": "application/gpx+xml",
    }

    with open(point_gpx_path, "rb") as f:
        body = f.read()

    req = requests.post(
        url,
        headers=headers,
        data=body,
    )

    req.raise_for_status()

    with open(output_path, "wb") as f:
        f.write(req.content)

    print(f"Map matching result saved to {output_path}")

    res =  json.loads(req.content)["paths"][0]

    return {
        "points": res["points"],
        "edge_ids": res["details"]["osm_way_id"],
    }

In [145]:
graphhopper_result = request_map_matching(
    point_gpx_path=gpx_path, output_path=DATA_BASE_PATH / "map_matched.json"
)
graphhopper_result

Map matching result saved to /home/jose_edsouza/Documentos/Faculdade/TCC/repo/dataset/newson-krumm/data/map_matched.json

{'points': 'aa}aHf`hhV?oIEcDByLKk@KS}@bB_@x@MVe@hA_@fAa@nA_@rAq@|@a@`@g@\\gEvBe@^W`@Qj@Ih@?v@B`@D\\H\\P^XX\\VpH`El@d@f@n@hA~Bh@fB\\p@d@nAV~@h@`CHpAJrD?dIKlo@E~EKpG?pCDzBHdBDn@VnCJ~@L|@VzA\\`B`@~Ap@tBt@nBx@hBpAxBlBbCh@p@lA`ArA~@zPvHl@p@lFhCjBz@hAd@~BfAlBfA`M`Gt@^l@VXwEBWH}ANcCZgDPsCHqB?mAEmBYeF[sFa@mGSmDK}BOeCEkAGe@cBkEcAcCy@sBmAmCUc@u@eAm@cAa@eA_@gAY{@c@qAOc@c@oAl@u@j@o@bBiBdFyFvAuA~BwB|@k@`Ag@`Aa@dAYlAWjAQxBWbBWz@Mf@OAe@@SFQn@mATk@ZcAxAqKn@mE`@{CX{BX_BLi@ZgATo@Zm@j@w@^e@rAsA\\Sf@SdAW|AQxC_@nC_@jAKt@KXMb@a@zB_ELWlG_LnAwBdDuGnA_Dn@uAbA_DjDuI|DuIdCgFxAsCpA{BVa@`@m@hCyChBoBzBiC~AeBhE{EvB}BbCqBlAw@zAy@ZU\\QjBi@n@OlBUh@CxAAbADdAJb@HpBp@fAh@fBvApClBnAr@zB|@tCnAv@b@~AbAdBrAdB`Bz@~@vAhBp@~@z@tAv@zAv@jBjB|E`DdK|@~Al@bA`BrBjGpHbAzAt@xA`EdLbDtIvAjDj@tAr@pAt@zAlCjEz@jAvApAfGpEr@d@jAx@XV~@t@hAlArC`D~@tA`@f@|@l@p@T~@N^A~@Kb@M~Bi@bDeAlEoAdGyA|C{@v@]bDq@lF{A\\GhACxBTpDb@fK|@r@J`B~@vBhAfAf@n@Lp@@rCIjA?bCUtTkA|He@vCKzAK|@Ch@DpAZlBh@`HnBnCt@xJtCrB^jCXlBNX?p@GZIVMRSPUP[N]Jc@Ls@ZsBNk@Z{@\\q@l@aAr@y@hKyKvCyCtBuBl@}@Zs@To@Tu@Lq@NmAl@aERiBb@qCJk@No@rBqGTe@Va@\\a@\\[f@a@f@UlBk@nBk@p@O@JFJLDJCFIDK?S~@]_A\\~@]xBk@rASxAOtAO|AMv@G`@E`@Ej@CdAEn@DRXLZB\\Gn@y@j@yDrBm@`@]Xy@|@kA|AuAtBcAbBqGnLsAxCaAbC]bAi@nB_ApDa@`Bc@vBUzAm@bFcA|Ie@rEU~B]zC]fDi@`D[fAyAzGs@pDmAlFM~@Ct@AfAJrF@fAAjACv@OdAU|BcAlIE\\[vCCp@A~@@t@DhAH`AN~@b@vBZx@Zp@r@lAzBbDz@fArBjDb@n@\\bAJZf@|BFl@BnA@lAEbAIfAKv@U`A[`Ae@|@e@j@iAnAOVKVI^Eb@Cx@?~CApEBXFXJRPTN^Lf@Df@VdCJbAXfCXvCLx@Rh@Z`@|@z@TbAFj@BdA?|@AzDCzBCj@SrBsAbJgBvGkB`Gm@|AW`AId@Ix@Ct@Av@@bADt@Fj@j@tEz@xHHn@JfALjAt@jGXrC@p@Aj@Il@Kj@Ud@_AxASp@E^CR?X@VBTFTJXLRRPXP`Bt@hAl@hGpCZRJNR^J^Fd@@h@A~@KtCChC?RNfBLlAP`BwB@mB@qA@{C@yAA{DIsGBoBAyA@oD?oD?cJAyAEUCa@Me@]_Ac@c@M_AE?uA?eB?kA@iIAqGBwDBuD\\wVHcFHuCLmGHgCZkDD]\\sB`@qBVwAJ}@HaB?y@Ao@Em@a@iEGuA?sAr@iPf@_LPoBLaAb@wAjAmCZg@f@e@h@_@NKxAk@PGTOPQLSJWR_AFm@@c@aBBmA@yABw@KcBCgAGoAG{@Ai@FqBM_@ASEYQWYO[Me@Ii@?m@Bg@F_@J]N[RWXOXIZ?XDRHTRNVN^Jf@Db@Dx@GlD?f@E~CGhCUtSCjC@vCDnCKbFY|OO~G]vSg@d\\IjEMnIK`HEpBSdPEnD[x^AjA?vADxBRvGTpFThG^fKFxArAf_@HnBD|ADxBDbC?hAChAIrAOfB_BbOKvAElB?rBBpAD~@XhDX|Bp@`EdEbWTvAZbCVjCHhCD`C?rBE~BQzDYbFcBlS_@rE_@bC_@tBc@hBi@hBw@|Bw@fB{@|AqEfHcAhBu@|Ac@lA}AvEaKzZ]dAyIjT_BdEg@zAe@zAsEhQq@pCkCfKu@nCm@jB{@`CsBdFeA`Cy@|Bm@nB[tAY`BQpAIpAEdC?pA@nAHxAZtDLbARbAXlA\\nAf@~ApDrKb@jAf@pAh@jB`@nCRnBH`BDvA@fAAlAGjIeCnyDKxO@pC?lGE`K?pEErOClGExPAhLAvHAbAEdSAbAGpAMpAa@tB[dA[|@Yp@k@x@{@|@_BzAo@d@mBdAoBfAqAz@e@d@_@f@_@t@c@dAQl@Or@Kt@MbAGr@EbAAfABnAFfAb@tDNfAFv@@l@Cf@Eb@Kh@Uj@[h@STYTGB]RYJe@F_CX{AXsAl@yClAo@\\yBxAk@b@}@~@cD|DeDxEe@n@iAbBuBlCcBzBgApAaAbAiAbAyBjByC~B{EzDsEbEo@p@}AbAe@V{@Z}@X}@NuAHi@?yA@}@EiASQEeDy@qEiAkG{As@QuFyAuAc@Us@]mA[wAi@cBs@uB_CiBwCaC@aA}AAg@k@e@{@k@{AUw@S_AKs@GcAAqDEoEAq@@oG?gGAaGAeGyD@o@Ja@BgC?eFCeFC?rE@pE`FBfF@jD?@rAhFAjFArEEP?J?|EEhFAfFAfFC`C@`@hAdAdDj@fBlA~DnAlE|A|E~AxEzAtE|A`FzA`Fr@|Bd@zA`@pAz@vCDR\\hAh@`BLX|AzE|ArEu@t@qApAqCfCmAfA}@x@mB`BuAjAiBhBaB~AcErDcA|@_@\\g@d@y@r@[`@mAfCgAzBsCdG_D~FaC~EWh@kAzBeAnBIPoBxDjCjDt@dAlAbB|BxDbCbDbCdDtApB\\d@cB`Es@xAiDrGcApBS\\OROLYQ[e@w@kAk@w@[c@}@qAS`@mC`FqBbEi@dAuBkDtBjDuBkDa@B?v@gF@wA?uCAcF@kFC}DEeA?y@?y@?aA??tA?rA?xAq@@uBBoDGmDA{AAg@GiDAkD@kDC_DCMDa@l@_@T_@BkD@aCBsBIqFEwC@{A?mFAsFAqJ?iJAoD?iDCgDA?eGwE?@sE?yE?iEAuE`AcCh@qAn@iBmABoA@aAByCAa@?wAAwB?gABsBDgAJ{@Bk@@{@BN_CN_Cd@mGl@eGb@uFFkA?eA@w@BwEsLU_FI_AAaBAoAGmAAgBEsAAw@Ag@AqCK}ACkAAwCG}CEmCAgAAfA@gAAgAA?yB@yD?iH?{B?mD?{@?yD?o@?mE?g@?yF?kF@oF@mF?oF@iC@kE@sECsEAwEDcF~B@bB?Z?rBE|CCzAEtAGn@GfAWdCI|BCjIF`B@`HB|NHlEBzBFbJd@tDRlAObA?xFHj@GZMZQX[PYVo@Pi@Nu@Do@?u@AiAE_AMmBP@rA?`C?G|FF}FaC?sA?e@AL~DFjALpADo@?u@AiAE_AMmBQiD[iEUsFWgFIeBGiBEmBC{BEiICuGCqAEoAK{AM{AQ{Ac@cDE[kAyIs@{FEa@K}AEqAAcA@gE?{CC_BIwAKaAC]o@sGm@mGKyAGwACqAC{B@uA@uAFyCN_FLuEJ{DhB{q@HoCHkBLkBNyAPuANcARgAp@{Cj@yBb@iB^kBZwBTmBbB{ShNwcBjLmwA^oE~@_L|AwR`AyLZsD`@wEXcEHeBFcC?uBG}BOiCKiAWqB]mB]}AWaA[aAIWi@sAm@oAq@mA{GyKs@mAo@mAq@_B]aAc@{A_BaHiBsImByIeBaIiBmI]gBSmAQ{AS}BI{AEiB?_B@}AFyBXgF^iGNuCNaCH}@XgCb@yCb@oBZgA`@oA^aA\\w@l@oA^q@`@o@vB_D~BaD`EqFrEiGhCeDb@c@h@g@pAcAjBmA~@e@z@c@bAo@`BiAvAgAz@cAp@_Ad@{@j@oAh@uAn@wBTcARcAL}@Fm@Ds@Bw@@qCAeGGcGAqB?_C@{ADkAFeALuBXgDTkBNaA^qBjCeNjCwNVsBNiBDmABuAAiD_@{Ka@kLGwBEwB@iCHgDd@_Jx@qPViGBcB@uDK{EU_Ea@kEk@yDo@iDyAgF_@uAcBaEo@sAmB_EwCcGaD_H_AsCo@{A_@cA]w@Qm@Mi@E_@?e@Dc@HYNYRUVO^GZ@VFVRTXR`@Lf@Dj@?hBCz@C\\GNQ\\{E?_CAwBAoCAA?mA@_A?q@?g@?}@Qi@Cm@?cJAmECBuEDkA',
 'edge_ids': [[0, 1, 1147800801],
  [1, 5, 1147800802],
  [5, 7, 1147800421],
  [7, 10, 1147800422],
  [10, 12, 1147800423],
  [12, 29, 1147800805],
  [29, 32, 1147800804],
  [32, 36, 1147800806],
  [36, 39, 1147800764],
  [39, 46, 1147800776],
  [46, 47, 1147800761],
  [47, 56, 1147800762],
  [56, 57, 1147800760],
  [57, 61, 1147800774],
  [61, 66, 1147801630],
  [66, 68, 1147801640],
  [68, 70, 1147801639],
  [70, 72, 1147801055],
  [72, 73, 1147801054],
  [73, 74, 1147801048],
  [74, 75, 1147801050],
  [75, 77, 1147801049],
  [77, 80, 1147801030],
  [80, 81, 1147801032],
  [81, 82, 1147801031],
  [82, 83, 1147801040],
  [83, 84, 1147801041],
  [84, 85, 1147801033],
  [85, 87, 1147801035],
  [87, 88, 1147801038],
  [88, 89, 1147801039],
  [89, 94, 1147801034],
  [94, 96, 1147801037],
  [96, 97, 1147801042],
  [97, 98, 1147801043],
  [98, 99, 1147801044],
  [99, 100, 1147801045],
  [100, 102, 1147801179],
  [102, 103, 1147801178],
  [103, 104, 1147801176],
  [104, 111, 1147801256],
  [111, 113, 1147801260],
  [113, 114, 1147801264],
  [114, 116, 1147801263],
  [116, 120, 1147801262],
  [120, 122, 1147801261],
  [122, 123, 1147801259],
  [123, 124, 1147801253],
  [124, 125, 1147801246],
  [125, 126, 1147801245],
  [126, 132, 1147801257],
  [132, 138, 1147801258],
  [138, 139, 1147801244],
  [139, 140, 1147801248],
  [140, 145, 1147801247],
  [145, 146, 1147801251],
  [146, 147, 1147801249],
  [147, 149, 1147801254],
  [149, 151, 1147801250],
  [151, 152, 1147801255],
  [152, 158, 1147801252],
  [158, 163, 1148400028],
  [163, 168, 1148400026],
  [168, 174, 1148400027],
  [174, 179, 1148400029],
  [179, 185, 1148400704],
  [185, 186, 1148400702],
  [186, 191, 1148400701],
  [191, 195, 1148400705],
  [195, 201, 1148400706],
  [201, 205, 1148400707],
  [205, 206, 1148400703],
  [206, 212, 1148400709],
  [212, 213, 1148400708],
  [213, 214, 1148400700],
  [214, 216, 1148400699],
  [216, 227, 1148400769],
  [227, 231, 1148400768],
  [231, 232, 1148400770],
  [232, 235, 1148400754],
  [235, 239, 1148400763],
  [239, 249, 1148400771],
  [249, 251, 1148400772],
  [251, 256, 1148400755],
  [256, 257, 1148400757],
  [257, 258, 1148400756],
  [258, 259, 1148400762],
  [259, 260, 1148400751],
  [260, 262, 1148400758],
  [262, 272, 1148400759],
  [272, 274, 1148400760],
  [274, 281, 1148400761],
  [281, 288, 1148400753],
  [288, 289, 1148400752],
  [289, 291, 1148400764],
  [291, 293, 1148400765],
  [293, 294, 1148400766],
  [294, 297, 1148400774],
  [297, 300, 1148400773],
  [300, 301, 1148400767],
  [301, 302, 1148401713],
  [302, 303, 1148401714],
  [303, 310, 1148401721],
  [310, 313, 1148400856],
  [313, 314, 1148400855],
  [314, 316, 1148400859],
  [316, 318, 1148400858],
  [318, 320, 1148400857],
  [320, 321, 1148400847],
  [321, 322, 1148400850],
  [322, 324, 1148400849],
  [324, 328, 1148401090],
  [328, 330, 1148401069],
  [330, 340, 1148401070],
  [340, 344, 1148401722],
  [344, 345, 1148400905],
  [345, 346, 1148400906],
  [346, 348, 1148400903],
  [348, 355, 1148400904],
  [355, 359, 1148400902],
  [359, 360, 1148400889],
  [360, 364, 1148400888],
  [364, 366, 1148400890],
  [366, 367, 1148400892],
  [367, 375, 1148400891],
  [375, 379, 1148400895],
  [379, 380, 1148400894],
  [380, 381, 1148400893],
  [381, 385, 1148401641],
  [385, 391, 1148401685],
  [391, 393, 1148401686],
  [393, 395, 1148401684],
  [395, 397, 1148401459],
  [397, 402, 1148401462],
  [402, 403, 1148401463],
  [403, 406, 1148401467],
  [406, 410, 1148401466],
  [410, 411, 1148401465],
  [411, 412, 1148401464],
  [412, 418, 1148401458],
  [418, 422, 1148401457],
  [422, 424, 1148401461],
  [424, 426, 1148401460],
  [426, 427, 1148401455],
  [427, 438, 1148401456],
  [438, 439, 1148401470],
  [439, 440, 1148401469],
  [440, 441, 1148401476],
  [441, 442, 1148401475],
  [442, 443, 1148401473],
  [443, 444, 1148401477],
  [444, 449, 1148401478],
  [449, 453, 1148401479],
  [453, 463, 1148401474],
  [463, 464, 1148401481],
  [464, 468, 1148401480],
  [468, 473, 1148400223],
  [473, 474, 1148400224],
  [474, 475, 1148101789],
  [475, 476, 1148101791],
  [476, 477, 1148101790],
  [477, 478, 1148101788],
  [478, 479, 1148101165],
  [479, 480, 1148101166],
  [480, 481, 1148101164],
  [481, 482, 1148101163],
  [482, 483, 1148101156],
  [483, 484, 1148101154],
  [484, 485, 1148101155],
  [485, 486, 1148101157],
  [486, 487, 1148101153],
  [487, 488, 1148101159],
  [488, 489, 1148101160],
  [489, 491, 1148101161],
  [491, 494, 1148101162],
  [494, 495, 1148101170],
  [495, 497, 1148101171],
  [497, 498, 1148101752],
  [498, 499, 1148101753],
  [499, 500, 1148400219],
  [500, 501, 1148400218],
  [501, 502, 1148400215],
  [502, 503, 1148400217],
  [503, 508, 1148400216],
  [508, 518, 1148400214],
  [518, 523, 1148401303],
  [523, 526, 1148401305],
  [526, 527, 1148401304],
  [527, 531, 1148401661],
  [531, 533, 1148401663],
  [533, 538, 1148401662],
  [538, 541, 1148401659],
  [541, 542, 1148401277],
  [542, 543, 1148401278],
  [543, 544, 1148401276],
  [544, 547, 1148401265],
  [547, 549, 1148400506],
  [549, 550, 1148400507],
  [550, 570, 1148400318],
  [570, 575, 1148400316],
  [575, 578, 1148400319],
  [578, 580, 1148400321],
  [580, 583, 1148400322],
  [583, 584, 1148400304],
  [584, 586, 1148400307],
  [586, 587, 1148400308],
  [587, 588, 1148400311],
  [588, 589, 1148400314],
  [589, 590, 1148400315],
  [590, 591, 1148400309],
  [591, 592, 1148400310],
  [592, 593, 1148400149],
  [593, 594, 1148100276],
  [594, 598, 1148100277],
  [598, 599, 1148100275],
  [599, 600, 1148100280],
  [600, 601, 1148100279],
  [601, 602, 1148100278],
  [602, 603, 1148100318],
  [603, 604, 1148100317],
  [604, 605, 1148100315],
  [605, 606, 1148100314],
  [606, 607, 1148100316],
  [607, 611, 1148100321],
  [611, 615, 1148100322],
  [615, 619, 1148100311],
  [619, 620, 1148100313],
  [620, 621, 1148100320],
  [621, 622, 1148100319],
  [622, 624, 1148100312],
  [624, 625, 1148100223],
  [625, 630, 1148100231],
  [630, 631, 1148100232],
  [631, 632, 1148100225],
  [632, 633, 1148100235],
  [633, 646, 1148100236],
  [646, 652, 1148100234],
  [652, 653, 1148100222],
  [653, 657, 1148100229],
  [657, 658, 1148100221],
  [658, 674, 1148100230],
  [674, 677, 1148100233],
  [677, 679, 1148100224],
  [679, 682, 1148100226],
  [682, 685, 1148100227],
  [685, 686, 1148100228],
  [686, 687, 1148000992],
  [687, 688, 1148000922],
  [688, 693, 1148000919],
  [693, 694, 1148000925],
  [694, 696, 1148000924],
  [696, 697, 1148000915],
  [697, 698, 1148000916],
  [698, 699, 1148000921],
  [699, 700, 1148000920],
  [700, 705, 1148000914],
  [705, 711, 1148000923],
  [711, 716, 1148000926],
  [716, 719, 1148000927],
  [719, 720, 1148000917],
  [720, 724, 1148000918],
  [724, 741, 1148000958],
  [741, 744, 1148000672],
  [744, 745, 1148008231],
  [745, 748, 1148000980],
  [748, 752, 1148000981],
  [752, 753, 1148000984],
  [753, 758, 1148000985],
  [758, 759, 1148000976],
  [759, 760, 1148000982],
  [760, 763, 1148000983],
  [763, 764, 1148000834],
  [764, 767, 1148000756],
  [767, 769, 1148000757],
  [769, 770, 1148000762],
  [770, 771, 1148000760],
  [771, 772, 1148000761],
  [772, 773, 1148000755],
  [773, 774, 1148000758],
  [774, 775, 1148000759],
  [775, 776, 1148000753],
  [776, 777, 1148000754],
  [777, 778, 1148000751],
  [778, 779, 1148000752],
  [779, 780, 1148000750],
  [780, 781, 1148001923],
  [781, 782, 1148001916],
  [782, 783, 1148001915],
  [783, 784, 1148003734],
  [784, 785, 1148003735],
  [785, 786, 1148003733],
  [786, 787, 1148003732],
  [787, 788, 1148001252],
  [788, 789, 1148002567],
  [789, 792, 1148003659],
  [792, 793, 1148003660],
  [793, 795, 1148003656],
  [795, 796, 1148003657],
  [796, 797, 1148003658],
  [797, 798, 1148003661],
  [798, 799, 1148003662],
  [799, 800, 1148003650],
  [800, 801, 1148003651],
  [801, 802, 1148003654],
  [802, 803, 1148003652],
  [803, 805, 1148002640],
  [805, 807, 1148002641],
  [807, 808, 1148002642],
  [808, 809, 1148002643],
  [809, 810, 1148005874],
  [810, 811, 1148005876],
  [811, 812, 1148002627],
  [812, 813, 1148002626],
  [813, 814, 1148002625],
  [814, 815, 1148003637],
  [815, 816, 1148003685],
  [816, 817, 1148003684],
  [817, 818, 1148002190],
  [818, 819, 1148002189],
  [819, 820, 1148002188],
  [820, 821, 1148002187],
  [821, 822, 1148002184],
  [822, 823, 1148002183],
  [823, 824, 1148002185],
  [824, 825, 1148002186],
  [825, 826, 1148001196],
  [826, 827, 1148001190],
  [827, 828, 1148001189],
  [828, 829, 1148001188],
  [829, 830, 1148001320],
  [830, 831, 1148001319],
  [831, 832, 1148001318],
  [832, 833, 1148001315],
  [833, 834, 1148001317],
  [834, 835, 1148001316],
  [835, 836, 1148001334],
  [836, 837, 1148001333],
  [837, 838, 1148001332],
  [838, 839, 1148001331],
  [839, 841, 1148001338],
  [841, 843, 1148001337],
  [843, 844, 1148001327],
  [844, 845, 1148001326],
  [845, 846, 1148001058],
  [846, 847, 1148001059],
  [847, 848, 1148001896],
  [848, 849, 1148001907],
  [849, 850, 1148001908],
  [850, 851, 1148001897],
  [851, 852, 1148001898],
  [852, 853, 1148001901],
  [853, 854, 1148001902],
  [854, 855, 1148001895],
  [855, 856, 1148001900],
  [856, 857, 1148001905],
  [857, 858, 1148001906],
  [858, 859, 1148001899],
  [859, 860, 1148001894],
  [860, 861, 1148001903],
  [861, 862, 1148001904],
  [862, 863, 1148000400],
  [863, 864, 1148000401],
  [864, 865, 1148000402],
  [865, 866, 1130900353],
  [866, 867, 1130900356],
  [867, 868, 1130900357],
  [868, 869, 1130900355],
  [869, 870, 1130900351],
  [870, 871, 1130900239],
  [871, 872, 1130900245],
  [872, 873, 1130900244],
  [873, 874, 1130900238],
  [874, 875, 1130900235],
  [875, 876, 1130900234],
  [876, 877, 1130900240],
  [877, 878, 1130900241],
  [878, 879, 1130900421],
  [879, 881, 1130900422],
  [881, 883, 1130900423],
  [883, 885, 1130900424],
  [885, 886, 1130902103],
  [886, 887, 1130902104],
  [887, 888, 1130902105],
  [888, 889, 1130902106],
  [889, 890, 1130902107],
  [890, 891, 1130902108],
  [891, 892, 1130900280],
  [892, 893, 1130900281],
  [893, 894, 1130900274],
  [894, 895, 1130900275],
  [895, 898, 1130902166],
  [898, 899, 1130900289],
  [899, 900, 1130900327],
  [900, 901, 1130901096],
  [901, 902, 1130901101],
  [902, 903, 1130901102],
  [903, 904, 1130901097],
  [904, 905, 1130901098],
  [905, 906, 1130901099],
  [906, 907, 1130901100],
  [907, 908, 1130901104],
  [908, 909, 1130901105],
  [909, 910, 1130901103],
  [910, 911, 1130900885],
  [911, 912, 1130900887],
  [912, 913, 1130900886],
  [913, 914, 1130900136],
  [914, 915, 1130900143],
  [915, 916, 1130900142],
  [916, 917, 1130900137],
  [917, 919, 1130900139],
  [919, 920, 1130900140],
  [920, 921, 1130900138],
  [921, 922, 1130900135],
  [922, 925, 1130900141],
  [925, 928, 1130900144],
  [928, 930, 1130900134],
  [930, 931, 1130900133],
  [931, 932, 1130900132],
  [932, 933, 1130302928],
  [933, 934, 1130302927],
  [934, 935, 1130302926],
  [935, 936, 1130302925],
  [936, 937, 1130302924],
  [937, 938, 1130302922],
  [938, 939, 1130302923],
  [939, 940, 1130302921],
  [940, 941, 1130305338],
  [941, 942, 1130305332],
  [942, 943, 1130304014],
  [943, 944, 1130304011],
  [944, 945, 1130304015],
  [945, 946, 1130304016],
  [946, 947, 1130302616],
  [947, 948, 1130302615],
  [948, 949, 1130302608],
  [949, 950, 1130302634],
  [950, 951, 1130302630],
  [951, 952, 1130304019],
  [952, 953, 1130304020],
  [953, 954, 1130304294],
  [954, 955, 1130304295],
  [955, 956, 1130304293],
  [956, 957, 1130303372],
  [957, 958, 1130303374],
  [958, 959, 1130303375],
  [959, 960, 1130303384],
  [960, 961, 1130303385],
  [961, 962, 1130303386],
  [962, 963, 1130303045],
  [963, 964, 1130303046],
  [964, 965, 1130303053],
  [965, 966, 1130303052],
  [966, 967, 1130303039],
  [967, 969, 1130303037],
  [969, 970, 1130303038],
  [970, 971, 1147400506],
  [971, 972, 1147402233],
  [972, 973, 1147402249],
  [973, 974, 1147402250],
  [974, 975, 1147402231],
  [975, 977, 1147402230],
  [977, 978, 1147402236],
  [978, 979, 1147402247],
  [979, 980, 1147402248],
  [980, 981, 1147402239],
  [981, 983, 1147402237],
  [983, 984, 1147402238],
  [984, 985, 1147402243],
  [985, 986, 1147402234],
  [986, 987, 1147402235],
  [987, 990, 1147402251],
  [990, 991, 1147402252],
  [991, 992, 1147400488],
  [992, 993, 1147400487],
  [993, 994, 1147400482],
  [994, 995, 1147400481],
  [995, 996, 1147400483],
  [996, 997, 1147400484],
  [997, 998, 1147400477],
  [998, 999, 1147400476],
  [999, 1000, 1147400479],
  [1000, 1001, 1147400478],
  [1001, 1002, 1147400470],
  [1002, 1003, 1147400471],
  [1003, 1004, 1147400472],
  [1004, 1005, 1147400473],
  [1005, 1006, 1147400474],
  [1006, 1007, 1147400475],
  [1007, 1008, 1147402091],
  [1008, 1009, 1147402092],
  [1009, 1010, 1147402093],
  [1010, 1011, 1147402095],
  [1011, 1012, 1147402094],
  [1012, 1013, 1147402500],
  [1013, 1014, 1147402499],
  [1014, 1015, 1147402493],
  [1015, 1018, 1147400722],
  [1018, 1021, 1147400721],
  [1021, 1025, 1147400699],
  [1025, 1026, 1147400698],
  [1026, 1027, 1147400640],
  [1027, 1030, 1147400641],
  [1030, 1031, 1147400639],
  [1031, 1037, 1147400708],
  [1037, 1039, 1147407420],
  [1039, 1042, 1147407419],
  [1042, 1047, 1147407418],
  [1047, 1048, 1147402018],
  [1048, 1049, 1147402017],
  [1049, 1050, 1147402016],
  [1050, 1052, 1147402008],
  [1052, 1053, 1147402016],
  [1053, 1054, 1147402017],
  [1054, 1055, 1147402018],
  [1055, 1058, 1147400649],
  [1058, 1064, 1147407418],
  [1064, 1066, 1147407417],
  [1066, 1067, 1147407425],
  [1067, 1068, 1147407424],
  [1068, 1078, 1147407407],
  [1078, 1079, 1147407406],
  [1079, 1080, 1147407408],
  [1080, 1091, 1147407409],
  [1091, 1093, 1147407410],
  [1093, 1099, 1147407411],
  [1099, 1102, 1147407402],
  [1102, 1103, 1147407401],
  [1103, 1104, 1147407404],
  [1104, 1113, 1147407405],
  [1113, 1120, 1147407403],
  [1120, 1121, 1147500201],
  [1121, 1122, 1147503773],
  [1122, 1124, 1147503774],
  [1124, 1125, 1148100205],
  [1125, 1126, 1148100198],
  [1126, 1133, 1148100199],
  [1133, 1139, 1148100197],
  [1139, 1143, 1147503766],
  [1143, 1150, 1147503767],
  [1150, 1152, 1147503737],
  [1152, 1153, 1147503738],
  [1153, 1164, 1147503740],
  [1164, 1165, 1147503741],
  [1165, 1168, 1147503707],
  [1168, 1170, 1147503710],
  [1170, 1175, 1147503708],
  [1175, 1180, 1147503709],
  [1180, 1181, 1147503712],
  [1181, 1182, 1147503711],
  [1182, 1184, 1147503713],
  [1184, 1188, 1148100136],
  [1188, 1189, 1148100135],
  [1189, 1197, 1148100134],
  [1197, 1198, 1148100133],
  [1198, 1199, 1148100138],
  [1199, 1205, 1148100137],
  [1205, 1207, 1148100132],
  [1207, 1212, 1148103696],
  [1212, 1214, 1148103697],
  [1214, 1218, 1148103698],
  [1218, 1225, 1148103699],
  [1225, 1232, 1148400275],
  [1232, 1237, 1148400274],
  [1237, 1241, 1148400273],
  [1241, 1242, 1148400272],
  [1242, 1247, 1148404256],
  [1247, 1249, 1148404254],
  [1249, 1253, 1148401846],
  [1253, 1264, 1148401845],
  [1264, 1273, 1148401844],
  [1273, 1274, 1148400013],
  [1274, 1275, 1148400012],
  [1275, 1276, 1148400011],
  [1276, 1277, 1148400009],
  [1277, 1278, 1148400022],
  [1278, 1279, 1147801155],
  [1279, 1280, 1147801156],
  [1280, 1281, 1147801153],
  [1281, 1282, 1147801154],
  [1282, 1285, 1147800845],
  [1285, 1286, 1147800842],
  [1286, 1287, 1147800843],
  [1287, 1289, 1147800892]]}

In [146]:
grapphopper_trajectory = [res[-1] + 883000000000 for res in graphhopper_result["edge_ids"]]
grapphopper_trajectory

[884147800801,
 884147800802,
 884147800421,
 884147800422,
 884147800423,
 884147800805,
 884147800804,
 884147800806,
 884147800764,
 884147800776,
 884147800761,
 884147800762,
 884147800760,
 884147800774,
 884147801630,
 884147801640,
 884147801639,
 884147801055,
 884147801054,
 884147801048,
 884147801050,
 884147801049,
 884147801030,
 884147801032,
 884147801031,
 884147801040,
 884147801041,
 884147801033,
 884147801035,
 884147801038,
 884147801039,
 884147801034,
 884147801037,
 884147801042,
 884147801043,
 884147801044,
 884147801045,
 884147801179,
 884147801178,
 884147801176,
 884147801256,
 884147801260,
 884147801264,
 884147801263,
 884147801262,
 884147801261,
 884147801259,
 884147801253,
 884147801246,
 884147801245,
 884147801257,
 884147801258,
 884147801244,
 884147801248,
 884147801247,
 884147801251,
 884147801249,
 884147801254,
 884147801250,
 884147801255,
 884147801252,
 884148400028,
 884148400026,
 884148400027,
 884148400029,
 884148400704,
 884148400702,
 884148400701,
 884148400705,
 884148400706,
 884148400707,
 884148400703,
 884148400709,
 884148400708,
 884148400700,
 884148400699,
 884148400769,
 884148400768,
 884148400770,
 884148400754,
 884148400763,
 884148400771,
 884148400772,
 884148400755,
 884148400757,
 884148400756,
 884148400762,
 884148400751,
 884148400758,
 884148400759,
 884148400760,
 884148400761,
 884148400753,
 884148400752,
 884148400764,
 884148400765,
 884148400766,
 884148400774,
 884148400773,
 884148400767,
 884148401713,
 884148401714,
 884148401721,
 884148400856,
 884148400855,
 884148400859,
 884148400858,
 884148400857,
 884148400847,
 884148400850,
 884148400849,
 884148401090,
 884148401069,
 884148401070,
 884148401722,
 884148400905,
 884148400906,
 884148400903,
 884148400904,
 884148400902,
 884148400889,
 884148400888,
 884148400890,
 884148400892,
 884148400891,
 884148400895,
 884148400894,
 884148400893,
 884148401641,
 884148401685,
 884148401686,
 884148401684,
 884148401459,
 884148401462,
 884148401463,
 884148401467,
 884148401466,
 884148401465,
 884148401464,
 884148401458,
 884148401457,
 884148401461,
 884148401460,
 884148401455,
 884148401456,
 884148401470,
 884148401469,
 884148401476,
 884148401475,
 884148401473,
 884148401477,
 884148401478,
 884148401479,
 884148401474,
 884148401481,
 884148401480,
 884148400223,
 884148400224,
 884148101789,
 884148101791,
 884148101790,
 884148101788,
 884148101165,
 884148101166,
 884148101164,
 884148101163,
 884148101156,
 884148101154,
 884148101155,
 884148101157,
 884148101153,
 884148101159,
 884148101160,
 884148101161,
 884148101162,
 884148101170,
 884148101171,
 884148101752,
 884148101753,
 884148400219,
 884148400218,
 884148400215,
 884148400217,
 884148400216,
 884148400214,
 884148401303,
 884148401305,
 884148401304,
 884148401661,
 884148401663,
 884148401662,
 884148401659,
 884148401277,
 884148401278,
 884148401276,
 884148401265,
 884148400506,
 884148400507,
 884148400318,
 884148400316,
 884148400319,
 884148400321,
 884148400322,
 884148400304,
 884148400307,
 884148400308,
 884148400311,
 884148400314,
 884148400315,
 884148400309,
 884148400310,
 884148400149,
 884148100276,
 884148100277,
 884148100275,
 884148100280,
 884148100279,
 884148100278,
 884148100318,
 884148100317,
 884148100315,
 884148100314,
 884148100316,
 884148100321,
 884148100322,
 884148100311,
 884148100313,
 884148100320,
 884148100319,
 884148100312,
 884148100223,
 884148100231,
 884148100232,
 884148100225,
 884148100235,
 884148100236,
 884148100234,
 884148100222,
 884148100229,
 884148100221,
 884148100230,
 884148100233,
 884148100224,
 884148100226,
 884148100227,
 884148100228,
 884148000992,
 884148000922,
 884148000919,
 884148000925,
 884148000924,
 884148000915,
 884148000916,
 884148000921,
 884148000920,
 884148000914,
 884148000923,
 884148000926,
 884148000927,
 884148000917,
 884148000918,
 884148000958,
 884148000672,
 884148008231,
 884148000980,
 884148000981,
 884148000984,
 884148000985,
 884148000976,
 884148000982,
 884148000983,
 884148000834,
 884148000756,
 884148000757,
 884148000762,
 884148000760,
 884148000761,
 884148000755,
 884148000758,
 884148000759,
 884148000753,
 884148000754,
 884148000751,
 884148000752,
 884148000750,
 884148001923,
 884148001916,
 884148001915,
 884148003734,
 884148003735,
 884148003733,
 884148003732,
 884148001252,
 884148002567,
 884148003659,
 884148003660,
 884148003656,
 884148003657,
 884148003658,
 884148003661,
 884148003662,
 884148003650,
 884148003651,
 884148003654,
 884148003652,
 884148002640,
 884148002641,
 884148002642,
 884148002643,
 884148005874,
 884148005876,
 884148002627,
 884148002626,
 884148002625,
 884148003637,
 884148003685,
 884148003684,
 884148002190,
 884148002189,
 884148002188,
 884148002187,
 884148002184,
 884148002183,
 884148002185,
 884148002186,
 884148001196,
 884148001190,
 884148001189,
 884148001188,
 884148001320,
 884148001319,
 884148001318,
 884148001315,
 884148001317,
 884148001316,
 884148001334,
 884148001333,
 884148001332,
 884148001331,
 884148001338,
 884148001337,
 884148001327,
 884148001326,
 884148001058,
 884148001059,
 884148001896,
 884148001907,
 884148001908,
 884148001897,
 884148001898,
 884148001901,
 884148001902,
 884148001895,
 884148001900,
 884148001905,
 884148001906,
 884148001899,
 884148001894,
 884148001903,
 884148001904,
 884148000400,
 884148000401,
 884148000402,
 884130900353,
 884130900356,
 884130900357,
 884130900355,
 884130900351,
 884130900239,
 884130900245,
 884130900244,
 884130900238,
 884130900235,
 884130900234,
 884130900240,
 884130900241,
 884130900421,
 884130900422,
 884130900423,
 884130900424,
 884130902103,
 884130902104,
 884130902105,
 884130902106,
 884130902107,
 884130902108,
 884130900280,
 884130900281,
 884130900274,
 884130900275,
 884130902166,
 884130900289,
 884130900327,
 884130901096,
 884130901101,
 884130901102,
 884130901097,
 884130901098,
 884130901099,
 884130901100,
 884130901104,
 884130901105,
 884130901103,
 884130900885,
 884130900887,
 884130900886,
 884130900136,
 884130900143,
 884130900142,
 884130900137,
 884130900139,
 884130900140,
 884130900138,
 884130900135,
 884130900141,
 884130900144,
 884130900134,
 884130900133,
 884130900132,
 884130302928,
 884130302927,
 884130302926,
 884130302925,
 884130302924,
 884130302922,
 884130302923,
 884130302921,
 884130305338,
 884130305332,
 884130304014,
 884130304011,
 884130304015,
 884130304016,
 884130302616,
 884130302615,
 884130302608,
 884130302634,
 884130302630,
 884130304019,
 884130304020,
 884130304294,
 884130304295,
 884130304293,
 884130303372,
 884130303374,
 884130303375,
 884130303384,
 884130303385,
 884130303386,
 884130303045,
 884130303046,
 884130303053,
 884130303052,
 884130303039,
 884130303037,
 884130303038,
 884147400506,
 884147402233,
 884147402249,
 884147402250,
 884147402231,
 884147402230,
 884147402236,
 884147402247,
 884147402248,
 884147402239,
 884147402237,
 884147402238,
 884147402243,
 884147402234,
 884147402235,
 884147402251,
 884147402252,
 884147400488,
 884147400487,
 884147400482,
 884147400481,
 884147400483,
 884147400484,
 884147400477,
 884147400476,
 884147400479,
 884147400478,
 884147400470,
 884147400471,
 884147400472,
 884147400473,
 884147400474,
 884147400475,
 884147402091,
 884147402092,
 884147402093,
 884147402095,
 884147402094,
 884147402500,
 884147402499,
 884147402493,
 884147400722,
 884147400721,
 884147400699,
 884147400698,
 884147400640,
 884147400641,
 884147400639,
 884147400708,
 884147407420,
 884147407419,
 884147407418,
 884147402018,
 884147402017,
 884147402016,
 884147402008,
 884147402016,
 884147402017,
 884147402018,
 884147400649,
 884147407418,
 884147407417,
 884147407425,
 884147407424,
 884147407407,
 884147407406,
 884147407408,
 884147407409,
 884147407410,
 884147407411,
 884147407402,
 884147407401,
 884147407404,
 884147407405,
 884147407403,
 884147500201,
 884147503773,
 884147503774,
 884148100205,
 884148100198,
 884148100199,
 884148100197,
 884147503766,
 884147503767,
 884147503737,
 884147503738,
 884147503740,
 884147503741,
 884147503707,
 884147503710,
 884147503708,
 884147503709,
 884147503712,
 884147503711,
 884147503713,
 884148100136,
 884148100135,
 884148100134,
 884148100133,
 884148100138,
 884148100137,
 884148100132,
 884148103696,
 884148103697,
 884148103698,
 884148103699,
 884148400275,
 884148400274,
 884148400273,
 884148400272,
 884148404256,
 884148404254,
 884148401846,
 884148401845,
 884148401844,
 884148400013,
 884148400012,
 884148400011,
 884148400009,
 884148400022,
 884147801155,
 884147801156,
 884147801153,
 884147801154,
 884147800845,
 884147800842,
 884147800843,
 884147800892]

In [147]:
ground_truth_trajectory = ground_truth_df["edge_id"].to_list()
ground_truth_trajectory

[884147800801,
 884147800802,
 884147800421,
 884147800422,
 884147800423,
 884147800805,
 884147800804,
 884147800806,
 884147800764,
 884147800776,
 884147800761,
 884147800762,
 884147800760,
 884147800774,
 884147801630,
 884147801640,
 884147801639,
 884147801055,
 884147801054,
 884147801048,
 884147801050,
 884147801049,
 884147801030,
 884147801032,
 884147801031,
 884147801040,
 884147801041,
 884147801033,
 884147801035,
 884147801038,
 884147801039,
 884147801034,
 884147801037,
 884147801042,
 884147801043,
 884147801044,
 884147801045,
 884147801179,
 884147801178,
 884147801176,
 884147801256,
 884147801260,
 884147801264,
 884147801263,
 884147801262,
 884147801261,
 884147801259,
 884147801253,
 884147801246,
 884147801245,
 884147801257,
 884147801258,
 884147801244,
 884147801248,
 884147801247,
 884147801251,
 884147801249,
 884147801254,
 884147801250,
 884147801255,
 884147801252,
 884148400028,
 884148400026,
 884148400027,
 884148400029,
 884148400704,
 884148400702,
 884148400701,
 884148400705,
 884148400706,
 884148400707,
 884148400703,
 884148400709,
 884148400708,
 884148400700,
 884148400699,
 884148400769,
 884148400768,
 884148400770,
 884148400754,
 884148400763,
 884148400771,
 884148400772,
 884148400755,
 884148400757,
 884148400756,
 884148400762,
 884148400751,
 884148400758,
 884148400759,
 884148400760,
 884148400761,
 884148400753,
 884148400752,
 884148400764,
 884148400765,
 884148400766,
 884148400774,
 884148400773,
 884148400767,
 884148401713,
 884148401714,
 884148401721,
 884148401719,
 884148401720,
 884148401721,
 884148400856,
 884148400855,
 884148400859,
 884148400858,
 884148400857,
 884148400847,
 884148400850,
 884148400849,
 884148401090,
 884148401069,
 884148401070,
 884148401722,
 884148400905,
 884148400906,
 884148400903,
 884148400904,
 884148400902,
 884148400889,
 884148400888,
 884148400890,
 884148400892,
 884148400891,
 884148400895,
 884148400894,
 884148400893,
 884148401641,
 884148401685,
 884148401686,
 884148401684,
 884148401459,
 884148401462,
 884148401463,
 884148401467,
 884148401466,
 884148401465,
 884148401464,
 884148401458,
 884148401457,
 884148401461,
 884148401460,
 884148401455,
 884148401456,
 884148401470,
 884148401469,
 884148401476,
 884148401475,
 884148401473,
 884148401477,
 884148401478,
 884148401479,
 884148401474,
 884148401481,
 884148401480,
 884148400223,
 884148400224,
 884148101789,
 884148101791,
 884148101790,
 884148101788,
 884148101165,
 884148101166,
 884148101164,
 884148101163,
 884148101156,
 884148101154,
 884148101155,
 884148101157,
 884148101153,
 884148101159,
 884148101160,
 884148101161,
 884148101162,
 884148101170,
 884148101171,
 884148101752,
 884148101753,
 884148400219,
 884148400218,
 884148400215,
 884148400217,
 884148400216,
 884148400214,
 884148401303,
 884148401305,
 884148401304,
 884148401661,
 884148401663,
 884148401662,
 884148401659,
 884148401277,
 884148401278,
 884148401276,
 884148401265,
 884148400506,
 884148400507,
 884148400318,
 884148400316,
 884148400319,
 884148400321,
 884148400322,
 884148400304,
 884148400307,
 884148400308,
 884148400311,
 884148400314,
 884148400315,
 884148400309,
 884148400310,
 884148400149,
 884148100276,
 884148100277,
 884148100275,
 884148100280,
 884148100279,
 884148100278,
 884148100318,
 884148100317,
 884148100315,
 884148100314,
 884148100316,
 884148100321,
 884148100322,
 884148100311,
 884148100313,
 884148100320,
 884148100319,
 884148100312,
 884148100223,
 884148100231,
 884148100232,
 884148100225,
 884148100235,
 884148100236,
 884148100234,
 884148100222,
 884148100229,
 884148100221,
 884148100230,
 884148100233,
 884148100224,
 884148100226,
 884148100227,
 884148100228,
 884148000992,
 884148000922,
 884148000919,
 884148000925,
 884148000924,
 884148000915,
 884148000916,
 884148000921,
 884148000920,
 884148000914,
 884148000923,
 884148000926,
 884148000927,
 884148000917,
 884148000918,
 884148000958,
 884148000672,
 884148008231,
 884148000980,
 884148000981,
 884148000984,
 884148000985,
 884148000976,
 884148000982,
 884148000983,
 884148000834,
 884148000756,
 884148000757,
 884148000762,
 884148000760,
 884148000761,
 884148000755,
 884148000758,
 884148000759,
 884148000753,
 884148000754,
 884148000763,
 884148000764,
 884148001915,
 884148003734,
 884148003735,
 884148003733,
 884148003732,
 884148003655,
 884148003659,
 884148003660,
 884148003656,
 884148003657,
 884148003658,
 884148003661,
 884148003662,
 884148003650,
 884148003651,
 884148003654,
 884148003652,
 884148002640,
 884148002641,
 884148002642,
 884148002643,
 884148005874,
 884148005876,
 884148002627,
 884148002626,
 884148002625,
 884148003637,
 884148003685,
 884148003684,
 884148002190,
 884148002189,
 884148002188,
 884148002187,
 884148002184,
 884148002183,
 884148002185,
 884148002186,
 884148001196,
 884148001190,
 884148001189,
 884148001188,
 884148001320,
 884148001319,
 884148001318,
 884148001315,
 884148001317,
 884148001316,
 884148001334,
 884148001333,
 884148001332,
 884148001331,
 884148001338,
 884148001337,
 884148001327,
 884148001326,
 884148001058,
 884148001059,
 884148001896,
 884148001907,
 884148001908,
 884148001897,
 884148001898,
 884148001901,
 884148001902,
 884148001895,
 884148001900,
 884148001905,
 884148001906,
 884148001899,
 884148001894,
 884148001903,
 884148001904,
 884148000400,
 884148000401,
 884148000402,
 884130900353,
 884130900356,
 884130900357,
 884130900355,
 884130900351,
 884130900239,
 884130900245,
 884130900244,
 884130900238,
 884130900235,
 884130900234,
 884130900240,
 884130900241,
 884130900421,
 884130900422,
 884130900423,
 884130900424,
 884130902103,
 884130902104,
 884130902105,
 884130902106,
 884130902107,
 884130902108,
 884130900280,
 884130900281,
 884130900274,
 884130900275,
 884130902166,
 884130900291,
 884130902167,
 884130900328,
 884130900327,
 884130901096,
 884130901101,
 884130901102,
 884130901097,
 884130901098,
 884130901099,
 884130901100,
 884130901104,
 884130901105,
 884130901103,
 884130900885,
 884130900887,
 884130900886,
 884130900136,
 884130900143,
 884130900142,
 884130900137,
 884130900139,
 884130900140,
 884130900138,
 884130900135,
 884130900141,
 884130900144,
 884130900134,
 884130900133,
 884130900132,
 884130302928,
 884130302927,
 884130302926,
 884130302925,
 884130302924,
 884130302922,
 884130302923,
 884130302921,
 884130305338,
 884130305332,
 884130304014,
 884130304011,
 884130304015,
 884130304016,
 884130302616,
 884130302615,
 884130302608,
 884130302634,
 884130302630,
 884130304019,
 884130304020,
 884130304294,
 884130304295,
 884130304293,
 884130303372,
 884130303374,
 884130303375,
 884130303384,
 884130303385,
 884130303386,
 884130303045,
 884130303046,
 884130303053,
 884130303052,
 884130303039,
 884130303037,
 884130303038,
 884147400506,
 884147402233,
 884147402249,
 884147402250,
 884147402231,
 884147402230,
 884147402236,
 884147402247,
 884147402248,
 884147402239,
 884147402237,
 884147402238,
 884147402243,
 884147402234,
 884147402235,
 884147402251,
 884147402252,
 884147400488,
 884147400487,
 884147400482,
 884147400481,
 884147400483,
 884147400484,
 884147400477,
 884147400476,
 884147400479,
 884147400478,
 884147400470,
 884147400471,
 884147400472,
 884147400473,
 884147400474,
 884147400475,
 884147402091,
 884147402092,
 884147402093,
 884147402095,
 884147402094,
 884147402500,
 884147402499,
 884147402493,
 884147400722,
 884147400721,
 884147400699,
 884147400698,
 884147400640,
 884147400641,
 884147400639,
 884147400708,
 884147407420,
 884147407419,
 884147407418,
 884147407417,
 884147407425,
 884147407424,
 884147407407,
 884147407406,
 884147407408,
 884147407409,
 884147407410,
 884147407411,
 884147407402,
 884147407401,
 884147407404,
 884147407405,
 884147407403,
 884147500201,
 884147503773,
 884147503774,
 884148100205,
 884148100198,
 884148100199,
 884148100197,
 884147503766,
 884147503767,
 884147503737,
 884147503738,
 884147503740,
 884147503741,
 884147503707,
 884147503710,
 884147503708,
 884147503709,
 884147503712,
 884147503711,
 884147503713,
 884148100136,
 884148100135,
 884148100134,
 884148100133,
 884148100138,
 884148100137,
 884148100132,
 884148103696,
 884148103697,
 884148103698,
 884148103699,
 884148400275,
 884148400274,
 884148400273,
 884148400272,
 884148404256,
 884148404254,
 884148401846,
 884148401845,
 884148401844,
 884148400013,
 884148400012,
 884148400011,
 884148400009,
 884148400022,
 884147801155,
 884147801156,
 884147801153,
 884147801154,
 884147800845,
 884147800842,
 884147800843,
 884147800892]

In [148]:
len(grapphopper_trajectory), len(ground_truth_trajectory)

(584, 576)

In [149]:
def calculate_distance(segs_id: int, rn_df: pd.DataFrame = route_network_df) -> float:
    seg = rn_df[rn_df["edge_id"].isin([segs_id])]["track_segs"].values

    if len(seg) != 1:
        raise ValueError(f"Expected one segment for edge_id {segs_id}, got {len(seg)}")
    
    seg = seg[0]

    total_distance = 0.0
    for i in range(len(seg) - 1):
        total_distance += geodesic(seg[i], seg[i + 1]).meters
        
    return total_distance

In [150]:
added = [seg for seg in grapphopper_trajectory if seg not in ground_truth_trajectory]
removed = [seg for seg in ground_truth_trajectory if seg not in grapphopper_trajectory]

print(f"Added segments: {len(added)}")
print(f"Removed segments: {len(removed)}")

Added segments: 16
Removed segments: 8

In [151]:
ground_truth_distance = sum(
    calculate_distance(seg_id, route_network_df) for seg_id in ground_truth_trajectory
)

added_distance = sum(
    calculate_distance(seg_id, route_network_df) for seg_id in added
)
removed_distance = sum(
    calculate_distance(seg_id, route_network_df) for seg_id in removed
)

print(f"Ground truth distance: {ground_truth_distance:.2f} m")
print(f"Added distance: {added_distance:.2f} m")
print(f"Removed distance: {removed_distance:.2f} m")

Ground truth distance: 80241.64 m
Added distance: 882.14 m
Removed distance: 597.60 m

In [152]:
def calculate_accuracy(gt_dist: float, added_dist: float, removed_dist: float) -> float:
    if gt_dist == 0:
        return 0.0
    return 1- (added_dist + removed_dist) / gt_dist

In [153]:
accuracy = calculate_accuracy(
    ground_truth_distance, added_distance, removed_distance
)

print(f"Accuracy: {accuracy:.2%}")

Accuracy: 98.16%